In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv(r"D:\Practice\Numpy\Practice\Dataset\4train.csv")

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [19]:
#1 Create a NumPy array from the Fare column and find the 5 highest fare values using NumPy. 

fare = df['Fare'].to_numpy()

print(np.sort(fare)[-5:])

[263.     263.     512.3292 512.3292 512.3292]


In [21]:
#2 Using the Fare NumPy array, find the indices of the 10 passengers with the highest fares using argsort().

print(np.argsort(fare)[-10:])

[299 742 311  88  27 438 341 737 679 258]


In [22]:
#3 Create a NumPy array from Pclass and find all unique passenger classes. 

pclass = df['Pclass'].to_numpy()

print(np.unique(pclass))

[1 2 3]


In [23]:
#4 Create a NumPy array from Survived and find the index positions of all passengers who survived. 

survived = df['Survived'].to_numpy()

print(np.where(survived == 1))

(array([  1,   2,   3,   8,   9,  10,  11,  15,  17,  19,  21,  22,  23,
        25,  28,  31,  32,  36,  39,  43,  44,  47,  52,  53,  55,  56,
        58,  61,  65,  66,  68,  74,  78,  79,  81,  82,  84,  85,  88,
        97,  98, 106, 107, 109, 123, 125, 127, 128, 133, 136, 141, 142,
       146, 151, 156, 161, 165, 166, 172, 183, 184, 186, 187, 190, 192,
       193, 194, 195, 198, 204, 207, 208, 209, 211, 215, 216, 218, 220,
       224, 226, 230, 233, 237, 241, 247, 248, 255, 256, 257, 258, 259,
       261, 267, 268, 269, 271, 272, 274, 275, 279, 283, 286, 288, 289,
       290, 291, 298, 299, 300, 301, 303, 305, 306, 307, 309, 310, 311,
       315, 316, 318, 319, 322, 323, 325, 327, 328, 329, 330, 334, 337,
       338, 340, 341, 345, 346, 347, 348, 356, 358, 359, 366, 367, 368,
       369, 370, 375, 376, 380, 381, 383, 387, 389, 390, 391, 393, 394,
       399, 400, 407, 412, 414, 416, 417, 426, 427, 429, 430, 431, 432,
       435, 437, 440, 443, 444, 445, 446, 447, 448, 449, 453, 4

In [27]:
#5 
"""
Create a NumPy matrix containing these columns in this exact order: 
Pclass, Age, SibSp, Parch, Fare 

Then display its shape. 
"""

plcass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()

mat = np.column_stack((plcass, age, sibsp, parch, fare))

mat.shape

(891, 5)

In [28]:
#6 Using the matrix from Q5, split it vertically into two equal parts using NumPy. 

print(np.array_split(mat,2))

[array([[ 3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 2.    , 28.    ,  0.    ,  0.    , 13.    ],
       [ 3.    ,     nan,  0.    ,  0.    ,  8.1125],
       [ 1.    ,  4.    ,  0.    ,  2.    , 81.8583]], shape=(446, 5)), array([[ 2.    , 13.    ,  0.    ,  1.    , 19.5   ],
       [ 1.    , 34.    ,  0.    ,  0.    , 26.55  ],
       [ 3.    ,  5.    ,  2.    ,  1.    , 19.2583],
       ...,
       [ 3.    ,     nan,  1.    ,  2.    , 23.45  ],
       [ 1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 3.    , 32.    ,  0.    ,  0.    ,  7.75  ]], shape=(445, 5))]


In [32]:
#7 Create separate NumPy arrays for Pclass, SibSp, and Parch, then join them horizontally into a single feature matrix using an appropriate NumPy joining method

mat = np.column_stack((pclass, sibsp, parch))

mat

array([[3, 1, 0],
       [1, 1, 0],
       [3, 0, 0],
       ...,
       [3, 1, 2],
       [1, 0, 0],
       [3, 0, 0]], shape=(891, 3))

In [33]:
#8 Increase every passenger's Fare by 10% using NumPy broadcasting, without using a loop. 

increase = fare + (fare * 10) / 100

print(increase)

[  7.975    78.41163   8.7175   58.41      8.855     9.30413  57.04875
  23.1825   12.24663  33.07788  18.37     29.205     8.855    34.4025
   8.63962  17.6      32.0375   14.3      19.8       7.9475   28.6
  14.3       8.83212  39.05     23.1825   34.52625   7.9475  289.3
   8.66712   8.68538  30.49288 161.17288   8.525    11.55     90.38788
  57.2       7.95212   8.855    19.8      12.36587  10.4225   23.1
   8.68538  45.73712   8.66712   8.855    17.05      8.525    23.84712
  19.58     43.65625   8.58     84.40212  28.6      68.17712  39.05
  11.55      7.95212  30.525    51.59      7.95212  88.       91.8225
  30.69     30.49288  16.77038  11.55      8.97413   8.7175    9.52875
  11.55     51.59     80.85     15.89962  62.14538   8.415     8.68538
   8.855    31.9      13.7225    9.9      10.45      8.56625  51.81
  11.55     17.435    37.8125    8.855   289.3       8.855     8.855
   8.63962  67.2925   22.6325    7.975     8.855    38.11962  69.69413
  25.3      28.6       8.685

In [42]:
#9 Create a NumPy Age array and replace every missing Age value with the overall mean Age, using NumPy vectorized operations.

age_mean = np.nanmean(age)

age[np.isnan(age)] = age_mean

print(age)

TypeError: 'numpy.bool' object does not support item assignment

In [41]:
#10
"""
Create a NumPy matrix containing: 
Survived, Pclass, Age, SibSp, Parch, Fare 
 
Then standardize the Fare column using vectorized NumPy operations so that you 
transform it using its mean and standard deviation.
"""

fare_mean = fare.mean()
fare_std = fare.std()

fare_standardized = (fare - fare_mean) / fare_std

print(fare_standardized)

[-5.02445171e-01  7.86845294e-01 -4.88854258e-01  4.20730236e-01
 -4.86337422e-01 -4.78116429e-01  3.95813561e-01 -2.24083121e-01
 -4.24256141e-01 -4.29555021e-02 -3.12172378e-01 -1.13845709e-01
 -4.86337422e-01 -1.87093118e-02 -4.90279793e-01 -3.26266659e-01
 -6.19988892e-02 -3.86670720e-01 -2.85997284e-01 -5.02948539e-01
 -1.24919787e-01 -3.86670720e-01 -4.86756223e-01  6.63597416e-02
 -2.24083121e-01 -1.64441595e-02 -5.02948539e-01  4.64700108e+00
 -4.89776426e-01 -4.89442190e-01 -9.02720170e-02  2.30172882e+00
 -4.92377828e-01 -4.37007438e-01  1.00606170e+00  3.98582080e-01
 -5.02863973e-01 -4.86337422e-01 -2.85997284e-01 -4.22073541e-01
 -4.57645492e-01 -2.25593223e-01 -4.89442190e-01  1.88762532e-01
 -4.89776426e-01 -4.86337422e-01 -3.36334002e-01 -4.92377828e-01
 -2.11917743e-01 -2.90024222e-01  1.50673744e-01 -4.91371093e-01
  8.96496787e-01 -1.24919787e-01  5.99510151e-01  6.63597416e-02
 -4.37007438e-01 -5.02863973e-01 -8.96840841e-02  2.95895176e-01
 -5.02863973e-01  9.62353