In [4]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"D:\Practice\Numpy\Practice\Dataset\4train.csv")

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [9]:
#1 Using the Fare NumPy array, find the 3 highest unique fare values. 

fare = df['Fare'].to_numpy()
unique_fare = np.unique(fare)

print(unique_fare[-3:][::-1])


[512.3292 263.     262.375 ]


In [13]:
#2 Using Age, find the index positions of all passengers whose age is between 20 and 30, using NumPy vectorized operations. 

age = df['Age'].to_numpy()

print(np.where((age >= 20) & (age <= 30)))

(array([  0,   2,   8,  12,  23,  34,  37,  41,  51,  53,  56,  57,  60,
        66,  69,  72,  73,  75,  79,  80,  81,  83,  88,  89,  90,  91,
        93,  97, 100, 102, 105, 106, 112, 113, 115, 117, 118, 120, 127,
       131, 133, 134, 135, 139, 141, 142, 146, 151, 157, 162, 169, 173,
       178, 199, 200, 207, 210, 212, 213, 216, 219, 221, 225, 227, 231,
       234, 242, 243, 244, 246, 247, 251, 253, 255, 257, 267, 271, 281,
       286, 287, 289, 290, 293, 294, 296, 308, 309, 310, 312, 313, 315,
       316, 320, 321, 322, 323, 336, 341, 342, 343, 345, 350, 353, 355,
       356, 361, 365, 369, 370, 373, 376, 377, 378, 391, 392, 393, 394,
       395, 398, 399, 401, 402, 403, 404, 408, 418, 421, 422, 423, 426,
       430, 436, 437, 441, 442, 443, 452, 455, 473, 474, 477, 478, 484,
       488, 491, 494, 498, 499, 501, 508, 509, 510, 514, 520, 521, 529,
       534, 537, 539, 551, 553, 554, 562, 565, 567, 580, 588, 600, 606,
       607, 608, 615, 617, 619, 620, 622, 623, 624, 627, 628, 6

In [14]:
#3 Using Pclass and Survived, create a NumPy matrix containing both columns and display its shape. 

pclass = df['Pclass'].to_numpy()
survived = df['Survived'].to_numpy()

mat = np.column_stack((pclass,survived))

mat

array([[3, 0],
       [1, 1],
       [3, 1],
       ...,
       [3, 0],
       [1, 1],
       [3, 0]], shape=(891, 2))

In [16]:
#4 Using SibSp and Parch, create a NumPy matrix and calculate the total family connections for each passenger using vectorized NumPy operations. 

sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()

family_connections = sibsp + parch
print(family_connections)

[ 1  1  0  1  0  0  0  4  2  1  2  0  0  6  0  0  5  0  1  0  0  0  0  0
  4  6  0  5  0  0  0  1  0  0  1  1  0  0  2  1  1  1  0  3  0  0  1  0
  2  1  5  0  1  1  1  0  0  0  3  7  0  0  1  5  0  2  0  0  6  2  0  7
  0  1  0  0  0  0  2  0  0  0  0  0  0  3  4  0  5  0  0  0  1  3  0  0
  0  1  1  1  0  0  1  0  2  0  0  0  0  1  0  1  0  1  0  0  0  1  1  6
  2  0  1  0  1  1  0  0  2  0  0  0  1  1  0  0  2  1  0  0  2  0  1  0
  0  2  0  4  2  0  0  1  0  2  0  1  0  0  0 10  1  0  0  0  5  2  1  5
  0  0  0  5  2  0  0  2  4  0  0  0 10  0  6  3  2  0  1  0  2  0  0  0
  1  2  0  0  0  1  0  0  0 10  0  0  0  1  1  0  0  0  0  0  0  0  1  1
  0  1  0  0  0  0  0  0  1  0  0  0  0  4  1  0  0  6  0  0  1  2  0  0
  1  1  0  0  0  2  0  2  2  1  0  2  0  1  2  2  0  0  0  1  0  6  2  0
  0  0  5  1  1  0  0  0  1  1  0  1  0  0  5  2  0  0  0  0  0  0  0  0
  0  0  0  1  0  0  0  0  0  3  0  1  0  2  0  0  0  3  0  1  1  0  0  4
  2  0  2  0  1  0  2  2  0  0  0  2 10  0  0  0  2

In [21]:
#5 Using Fare, find the indices of the 10 passengers with the lowest non-zero fares using argsort(). 

fare = df['Fare'].to_numpy()

indices = np.where(fare > 0)[0]

sorted_indices = indices[np.argsort(fare[indices])]

print(sorted_indices[:10])

[378 872 326 843 818 202 371 143 654 411]


In [23]:
#6 Using the Pclass, SibSp, and Parch arrays, create a feature matrix and transpose it for feature-wise analysis.

pclass = df['Pclass'].to_numpy() 
sibsp = df['SibSp'].to_numpy() 
parch = df['Parch'].to_numpy() 

mat = np.column_stack((pclass,sibsp,parch))

mat.transpose() 

array([[3, 1, 3, ..., 3, 1, 3],
       [1, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 2, 0, 0]], shape=(3, 891))

In [ ]:
#7 Using the Fare array, increase every fare by 20% for passengers who paid more than 100, while leaving all other fares unchanged. Use NumPy vectorized operations without a loop. 

fare = df['Fare'].to_numpy()

increase = np.where(fare > 100, fare + (fare * 20) / 100, fare)

print(increase)

[  7.25     71.2833    7.925    53.1       8.05      8.4583   51.8625
  21.075    11.1333   30.0708   16.7      26.55      8.05     31.275
   7.8542   16.       29.125    13.       18.        7.225    26.
  13.        8.0292   35.5      21.075    31.3875    7.225   315.6
   7.8792    7.8958   27.7208  175.82496   7.75     10.5      82.1708
  52.        7.2292    8.05     18.       11.2417    9.475    21.
   7.8958   41.5792    7.8792    8.05     15.5       7.75     21.6792
  17.8      39.6875    7.8      76.7292   26.       61.9792   35.5
  10.5       7.2292   27.75     46.9       7.2292   80.       83.475
  27.9      27.7208   15.2458   10.5       8.1583    7.925     8.6625
  10.5      46.9      73.5      14.4542   56.4958    7.65      7.8958
   8.05     29.       12.475     9.        9.5       7.7875   47.1
  10.5      15.85     34.375     8.05    315.6       8.05      8.05
   7.8542   61.175    20.575     7.25      8.05     34.6542   63.3583
  23.       26.        7.8958    7.8958  

In [27]:
#8 Using the Age array, calculate the mean age separately for passengers in each Pclass using NumPy operations. 

age = df['Age'].to_numpy()
pclass = df['Pclass'].to_numpy()

print(np.nanmean(age[pclass == 1]))
print(np.nanmean(age[pclass == 2]))
print(np.nanmean(age[pclass == 3]))

38.233440860215055
29.87763005780347
25.14061971830986


In [29]:
#9 
"""
Create a NumPy matrix containing: 
Survived, Pclass, Age, SibSp, Parch, Fare 

Then split the matrix into two row-wise parts using NumPy.
"""

survived = df['Survived'].to_numpy()
pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()

mat = np.column_stack((survived,pclass, age, sibsp, parch, fare))

print(np.array_split(mat,2))

[array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 1.    ,  2.    , 28.    ,  0.    ,  0.    , 13.    ],
       [ 1.    ,  3.    ,     nan,  0.    ,  0.    ,  8.1125],
       [ 1.    ,  1.    ,  4.    ,  0.    ,  2.    , 81.8583]],
      shape=(446, 6)), array([[ 1.    ,  2.    , 13.    ,  0.    ,  1.    , 19.5   ],
       [ 1.    ,  1.    , 34.    ,  0.    ,  0.    , 26.55  ],
       [ 1.    ,  3.    ,  5.    ,  2.    ,  1.    , 19.2583],
       ...,
       [ 0.    ,  3.    ,     nan,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    , 32.    ,  0.    ,  0.    ,  7.75  ]],
      shape=(445, 6))]


In [30]:
#10 Using the Fare array, calculate the z-score standardized Fare values using NumPy vectorized operations, then verify that the standardized array has a mean approximately equal to 0.

mean = np.mean(fare)
std = np.std(fare)

z_score = (fare - mean) / std

print(z_score)
print(np.mean(z_score))

[-5.02445171e-01  7.86845294e-01 -4.88854258e-01  4.20730236e-01
 -4.86337422e-01 -4.78116429e-01  3.95813561e-01 -2.24083121e-01
 -4.24256141e-01 -4.29555021e-02 -3.12172378e-01 -1.13845709e-01
 -4.86337422e-01 -1.87093118e-02 -4.90279793e-01 -3.26266659e-01
 -6.19988892e-02 -3.86670720e-01 -2.85997284e-01 -5.02948539e-01
 -1.24919787e-01 -3.86670720e-01 -4.86756223e-01  6.63597416e-02
 -2.24083121e-01 -1.64441595e-02 -5.02948539e-01  4.64700108e+00
 -4.89776426e-01 -4.89442190e-01 -9.02720170e-02  2.30172882e+00
 -4.92377828e-01 -4.37007438e-01  1.00606170e+00  3.98582080e-01
 -5.02863973e-01 -4.86337422e-01 -2.85997284e-01 -4.22073541e-01
 -4.57645492e-01 -2.25593223e-01 -4.89442190e-01  1.88762532e-01
 -4.89776426e-01 -4.86337422e-01 -3.36334002e-01 -4.92377828e-01
 -2.11917743e-01 -2.90024222e-01  1.50673744e-01 -4.91371093e-01
  8.96496787e-01 -1.24919787e-01  5.99510151e-01  6.63597416e-02
 -4.37007438e-01 -5.02863973e-01 -8.96840841e-02  2.95895176e-01
 -5.02863973e-01  9.62353