In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"D:\Practice\Numpy\Practice\Dataset\4train.csv")

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [7]:
#1 Using the Fare NumPy array, find the 5 most common fare values and their frequencies using NumPy.

fare = df['Fare'].to_numpy()

unique, counts = np.unique(fare, return_counts=True)

top5 = np.argsort(counts)[-5:][::-1]

print("Top 5 most common fares:")
print(unique[top5])

print("Their frequencies:")
print(counts[top5])

Top 5 most common fares:
[ 8.05   13.      7.8958  7.75   26.    ]
Their frequencies:
[43 42 38 34 31]


In [17]:
#2 Using the Age NumPy array, find the minimum, maximum, and mean age, while ignoring missing values.

age = df['Age'].to_numpy()

print(f"Min = {np.nanmin(age)}")
print(f"Max = {np.nanmax(age)}")
print(f"Mean = {np.nanmean(age)}")

Min = 0.42
Max = 80.0
Mean = 29.69911764705882


In [21]:
#3 Using the Pclass NumPy array, find the number of passengers in each unique passenger class using NumPy. 

pclass = df['Pclass'].to_numpy()

classes, counts = np.unique(pclass, return_counts=True)

print(classes)
print(counts)

[1 2 3]
[216 184 491]


In [26]:
#4 Using Survived and Pclass, create a NumPy matrix and calculate the total number of survivors for each passenger class.

survived = df['Survived'].to_numpy()
pclass = df['Pclass'].to_numpy()

mat = np.column_stack((survived, pclass))

print(np.sum((survived == 1) & (pclass == 1)))
print(np.sum((survived == 1) & (pclass == 2)))
print(np.sum((survived == 1) & (pclass == 3)))

136
87
119


In [28]:
#5 Using the Fare NumPy array, find the indices of passengers whose fare is above the overall mean fare.

fare = df['Fare'].to_numpy()

print(np.where(fare > fare.mean()))

(array([  1,   3,   6,  23,  27,  31,  34,  35,  43,  50,  52,  54,  55,
        59,  61,  62,  71,  72,  74,  83,  86,  88,  92,  96,  97, 102,
       110, 118, 120, 124, 137, 139, 145, 147, 151, 155, 159, 164, 166,
       169, 170, 180, 183, 185, 195, 201, 215, 218, 224, 230, 245, 248,
       256, 257, 258, 262, 266, 268, 269, 275, 290, 291, 297, 299, 305,
       306, 307, 309, 310, 311, 318, 319, 324, 325, 329, 332, 334, 336,
       337, 339, 341, 351, 356, 366, 369, 370, 373, 375, 377, 380, 383,
       385, 386, 390, 393, 412, 416, 434, 435, 436, 438, 445, 453, 457,
       462, 475, 480, 484, 486, 493, 496, 498, 504, 505, 509, 513, 515,
       520, 523, 527, 537, 539, 540, 544, 549, 550, 556, 557, 558, 571,
       577, 581, 583, 585, 587, 591, 596, 599, 602, 608, 609, 615, 618,
       621, 625, 627, 638, 641, 643, 645, 647, 655, 659, 660, 665, 669,
       670, 671, 678, 679, 681, 683, 684, 685, 686, 689, 690, 692, 698,
       700, 708, 710, 712, 716, 720, 724, 730, 736, 737, 741, 7

In [35]:
#6 Using Age and Pclass, create a NumPy matrix containing both features and sort the rows by Age.

age = df['Age'].to_numpy()
pclass = df['Pclass'].to_numpy()

mat = np.column_stack((age, pclass))

sorted_mat = mat[np.argsort(mat[:, 0])]

print(sorted_mat)

[[0.42 3.  ]
 [0.67 2.  ]
 [0.75 3.  ]
 ...
 [ nan 3.  ]
 [ nan 2.  ]
 [ nan 3.  ]]


In [36]:
#7 Using the Fare array, create a new NumPy array where fares greater than 100 are replaced with 100, while all other fares remain unchanged.

fare = df['Fare'].to_numpy()

print(np.where(fare > 100, 100, fare))


[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  100.       7.8792   7.8958  27.7208 100.
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 100.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.2875   8.6542
   7.925    7.8958   7.65     7.775    7.8958  24.15    52.      14.4542
   8.0

In [46]:
#8 Using Age, replace missing values with the median age instead of the mean, using NumPy vectorized operations. 

age = df['Age'].to_numpy()

median_age = np.nanmedian(age)

age[np.isnan(age)] = median_age

print(age)

ValueError: assignment destination is read-only

In [61]:
#9 Create a NumPy feature matrix containing Pclass, Age, SibSp, Parch, and Fare. Standardize the Age and Fare columns using vectorized NumPy operations. 

# Convert columns to NumPy arrays
pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy().copy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()

# Replace missing Age values with the median Age
age[np.isnan(age)] = np.nanmedian(age)

# Create the feature matrix
mat = np.column_stack((pclass, age, sibsp, parch, fare))

# Standardize Age
age_mean = np.mean(mat[:, 1])
age_std = np.std(mat[:, 1])
mat[:, 1] = (mat[:, 1] - age_mean) / age_std

# Standardize Fare
fare_mean = np.mean(mat[:, 4])
fare_std = np.std(mat[:, 4])
mat[:, 4] = (mat[:, 4] - fare_mean) / fare_std

print(mat)

[[ 3.         -0.56573646  1.          0.         -0.50244517]
 [ 1.          0.66386103  1.          0.          0.78684529]
 [ 3.         -0.25833709  0.          0.         -0.48885426]
 ...
 [ 3.         -0.1046374   1.          2.         -0.17626324]
 [ 1.         -0.25833709  0.          0.         -0.04438104]
 [ 3.          0.20276197  0.          0.         -0.49237783]]


In [73]:
#10 Create a NumPy feature matrix containing Survived, Pclass, Age, SibSp, Parch, and Fare. Normalize the Fare column using min-max normalization so that its values are between 0 and 1.

survived = df['Survived'].to_numpy()
pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy().copy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()

# Replace missing Age values
age[np.isnan(age)] = np.nanmedian(age)

# Create feature matrix
mat = np.column_stack((survived, pclass, age, sibsp, parch, fare))

# Min-max normalization of Fare
fare_min = np.min(mat[:, -1])
fare_max = np.max(mat[:, -1])

mat[:, -1] = (mat[:, -1] - fare_min) / (fare_max - fare_min)

print(mat)

[[0.00000000e+00 3.00000000e+00 2.20000000e+01 1.00000000e+00
  0.00000000e+00 1.41510576e-02]
 [1.00000000e+00 1.00000000e+00 3.80000000e+01 1.00000000e+00
  0.00000000e+00 1.39135735e-01]
 [1.00000000e+00 3.00000000e+00 2.60000000e+01 0.00000000e+00
  0.00000000e+00 1.54685698e-02]
 ...
 [0.00000000e+00 3.00000000e+00 2.80000000e+01 1.00000000e+00
  2.00000000e+00 4.57713517e-02]
 [1.00000000e+00 1.00000000e+00 2.60000000e+01 0.00000000e+00
  0.00000000e+00 5.85561003e-02]
 [0.00000000e+00 3.00000000e+00 3.20000000e+01 0.00000000e+00
  0.00000000e+00 1.51269926e-02]]
