In [13]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"D:\Practice\Numpy\Practice\Dataset\4train.csv")

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [14]:
#1 Create a NumPy array from Fare and find the 5 most frequent Fare values along with their frequencies.

fare = df['Fare'].to_numpy()

unique ,counts = np.unique(fare, return_counts=True)

top5 = np.argsort(counts)[-5:][::-1]

print(unique[top5])
print(counts[top5])

[ 8.05   13.      7.8958  7.75   26.    ]
[43 42 38 34 31]


In [15]:
#2 Create a NumPy array from Age and find the index positions of passengers whose age is between 18 and 25, excluding missing ages.

age = df['Age'].to_numpy()

print(np.where((age >= 18) & (age <= 25)))

(array([  0,  12,  27,  37,  38,  44,  49,  51,  56,  60,  67,  72,  75,
        80,  88,  89,  91,  97, 102, 106, 112, 113, 115, 118, 120, 127,
       131, 134, 135, 136, 139, 141, 142, 143, 144, 145, 151, 173, 175,
       191, 192, 199, 204, 210, 212, 225, 226, 227, 228, 234, 238, 243,
       246, 247, 267, 271, 283, 287, 289, 291, 293, 294, 296, 302, 310,
       311, 316, 320, 323, 341, 343, 345, 350, 353, 356, 369, 370, 371,
       372, 373, 376, 378, 379, 385, 391, 393, 394, 395, 398, 402, 404,
       408, 417, 421, 424, 427, 436, 437, 441, 442, 473, 474, 478, 484,
       491, 494, 498, 499, 501, 505, 514, 521, 529, 539, 546, 553, 554,
       565, 566, 575, 580, 585, 588, 600, 608, 615, 622, 623, 624, 627,
       640, 641, 646, 649, 651, 652, 654, 655, 658, 664, 666, 675, 676,
       677, 682, 685, 687, 688, 693, 700, 702, 703, 708, 710, 715, 725,
       728, 729, 733, 734, 742, 743, 748, 753, 757, 762, 770, 775, 784,
       785, 786, 794, 807, 816, 833, 834, 836, 840, 855, 858, 8

In [16]:
#3 Create NumPy arrays for Survived and Pclass and calculate the survival rate of Class 1 passengers.

survived = df['Survived'].to_numpy()
pclass = df['Pclass'].to_numpy()

class1_survived = np.sum((survived == 1) & (pclass == 1))
class1_total = np.sum(pclass == 1)

survival_rate = (class1_survived / class1_total) * 100

print(survival_rate)

62.96296296296296


In [17]:
#4 Create NumPy arrays for SibSp and Parch and create a new array representing the total family connections for every passenger.

sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()

fa_con = sibsp + parch

print(fa_con)

[ 1  1  0  1  0  0  0  4  2  1  2  0  0  6  0  0  5  0  1  0  0  0  0  0
  4  6  0  5  0  0  0  1  0  0  1  1  0  0  2  1  1  1  0  3  0  0  1  0
  2  1  5  0  1  1  1  0  0  0  3  7  0  0  1  5  0  2  0  0  6  2  0  7
  0  1  0  0  0  0  2  0  0  0  0  0  0  3  4  0  5  0  0  0  1  3  0  0
  0  1  1  1  0  0  1  0  2  0  0  0  0  1  0  1  0  1  0  0  0  1  1  6
  2  0  1  0  1  1  0  0  2  0  0  0  1  1  0  0  2  1  0  0  2  0  1  0
  0  2  0  4  2  0  0  1  0  2  0  1  0  0  0 10  1  0  0  0  5  2  1  5
  0  0  0  5  2  0  0  2  4  0  0  0 10  0  6  3  2  0  1  0  2  0  0  0
  1  2  0  0  0  1  0  0  0 10  0  0  0  1  1  0  0  0  0  0  0  0  1  1
  0  1  0  0  0  0  0  0  1  0  0  0  0  4  1  0  0  6  0  0  1  2  0  0
  1  1  0  0  0  2  0  2  2  1  0  2  0  1  2  2  0  0  0  1  0  6  2  0
  0  0  5  1  1  0  0  0  1  1  0  1  0  0  5  2  0  0  0  0  0  0  0  0
  0  0  0  1  0  0  0  0  0  3  0  1  0  2  0  0  0  3  0  1  1  0  0  4
  2  0  2  0  1  0  2  2  0  0  0  2 10  0  0  0  2

In [18]:
#5 Create a NumPy array from Fare and find the indices of the 10 passengers who paid the highest fares, ordered from highest to lowest fare. 

fare = df['Fare'].to_numpy()

highest_fare = np.argsort(fare)[-10:][::-1]

print(highest_fare)

[258 679 737 341 438  27  88 311 742 299]


In [19]:
#6 Create a matrix containing Pclass, Age, SibSp, Parch, and Fare. Replace missing Age values with the median Age and sort the complete matrix by Fare from lowest to highest.

pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()

age = np.where(np.isnan(age), np.median(age), age)

mat = np.column_stack((pclass,age,sibsp,parch,fare))

sorted_mat = mat[np.argsort(mat[:, 4])]

print(sorted_mat)

[[  1.          nan   0.       0.       0.    ]
 [  1.      39.       0.       0.       0.    ]
 [  2.          nan   0.       0.       0.    ]
 ...
 [  1.      35.       0.       0.     512.3292]
 [  1.      36.       0.       1.     512.3292]
 [  1.      35.       0.       0.     512.3292]]


In [20]:
#7 
"""
Create a NumPy array from Fare and apply this rule using vectorized operations: 
 Fare > 200 → increase by 5%  
 Fare ≤ 200 → increase by 10% 
"""

fare = df['Fare'].to_numpy()

new = np.where(fare > 200, fare + (fare * 5) / 100, fare + (fare * 10) / 100)

print(new)

[  7.975     78.41163    8.7175    58.41       8.855      9.30413
  57.04875   23.1825    12.24663   33.07788   18.37      29.205
   8.855     34.4025     8.63962   17.6       32.0375    14.3
  19.8        7.9475    28.6       14.3        8.83212   39.05
  23.1825    34.52625    7.9475   276.15       8.66712    8.68538
  30.49288  161.17288    8.525     11.55      90.38788   57.2
   7.95212    8.855     19.8       12.36587   10.4225    23.1
   8.68538   45.73712    8.66712    8.855     17.05       8.525
  23.84712   19.58      43.65625    8.58      84.40212   28.6
  68.17712   39.05      11.55       7.95212   30.525     51.59
   7.95212   88.        91.8225    30.69      30.49288   16.77038
  11.55       8.97413    8.7175     9.52875   11.55      51.59
  80.85      15.89962   62.14538    8.415      8.68538    8.855
  31.9       13.7225     9.9       10.45       8.56625   51.81
  11.55      17.435     37.8125     8.855    276.15       8.855
   8.855      8.63962   67.2925    22.6325    

In [21]:
#8 Create NumPy arrays for Age and Pclass. Replace missing Age values with the median Age of their respective passenger class.

age = df['Age'].to_numpy()
pclass = df['Pclass'].to_numpy()

median1 = np.nanmedian(age[pclass == 1])
median2 = np.nanmedian(age[pclass == 2])
median3 = np.nanmedian(age[pclass == 3])

age = np.where(np.isnan(age) & (pclass == 1), median1, age)
age = np.where(np.isnan(age) & (pclass == 2), median1, age)
age = np.where(np.isnan(age) & (pclass == 3), median1, age)

print(age)

[22.   38.   26.   35.   35.   37.   54.    2.   27.   14.    4.   58.
 20.   39.   14.   55.    2.   37.   31.   37.   35.   34.   15.   28.
  8.   38.   37.   19.   37.   37.   40.   37.   37.   66.   28.   42.
 37.   21.   18.   14.   40.   27.   37.    3.   19.   37.   37.   37.
 37.   18.    7.   21.   49.   29.   65.   37.   21.   28.5   5.   11.
 22.   38.   45.    4.   37.   37.   29.   19.   17.   26.   32.   16.
 21.   26.   32.   25.   37.   37.    0.83 30.   22.   29.   37.   28.
 17.   33.   16.   37.   23.   24.   29.   20.   46.   26.   59.   37.
 71.   23.   34.   34.   28.   37.   21.   33.   37.   28.   21.   37.
 38.   37.   47.   14.5  22.   20.   17.   21.   70.5  29.   24.    2.
 21.   37.   32.5  32.5  54.   12.   37.   24.   37.   45.   33.   20.
 47.   29.   25.   23.   19.   37.   16.   24.   37.   22.   24.   19.
 18.   19.   27.    9.   36.5  42.   51.   22.   55.5  40.5  37.   51.
 16.   30.   37.   37.   44.   40.   26.   17.    1.    9.   37.   45.
 37.  

In [24]:
#9 Create a feature matrix containing Pclass, Age, SibSp, Parch, and Fare. Replace missing Age values with the median and standardize both Age and Fare using vectorized operations. 

pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()

age = np.where(np.isnan(age), np.nanmedian(age), age)

age = (age - np.nanmean(age)) / np.nanstd(age)
fare = (fare - np.nanmean(fare)) / np.nanstd(fare)

mat = np.column_stack((pclass, age, sibsp, parch, fare))
print(mat)

[[ 3.         -0.56573646  1.          0.         -0.50244517]
 [ 1.          0.66386103  1.          0.          0.78684529]
 [ 3.         -0.25833709  0.          0.         -0.48885426]
 ...
 [ 3.         -0.1046374   1.          2.         -0.17626324]
 [ 1.         -0.25833709  0.          0.         -0.04438104]
 [ 3.          0.20276197  0.          0.         -0.49237783]]


In [ ]:
#10 Create a feature matrix containing Survived, Pclass, Age, SibSp, Parch, and Fare. Replace missing Age values with its median, min-max normalize Fare, and then transpose the final matrix. 

survived = df['Survived'].to_numpy()
pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()

fare_min = np.min(fare)
fare_max = np.max(fare)

fare = (fare - fare_min) / (fare_max - fare_min)

age = np.where(np.isnan(age), np.nanmedian(age), age)

mat = np.column_stack((survived, pclass, age, sibsp, parch, fare))

mat = mat.T

print(mat)

[[0.00000000e+00 1.00000000e+00 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [3.00000000e+00 1.00000000e+00 3.00000000e+00 ... 3.00000000e+00
  1.00000000e+00 3.00000000e+00]
 [2.20000000e+01 3.80000000e+01 2.60000000e+01 ... 2.80000000e+01
  2.60000000e+01 3.20000000e+01]
 [1.00000000e+00 1.00000000e+00 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 2.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.41510576e-02 1.39135735e-01 1.54685698e-02 ... 4.57713517e-02
  5.85561003e-02 1.51269926e-02]]
