In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"D:\Practice\Numpy\Practice\Dataset\4train.csv")

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [6]:
#1 
"""
Create: 
Pclass_Avg_Fare 
using groupby() + transform(). 
 
Then create: 
Fare_Difference 
 
using: 
Fare - Pclass_Avg_Fare 
 
Display: 
Name, Pclass, Fare, Pclass_Avg_Fare, Fare_Difference 
for the first 10 passengers.
"""

df['Pclass_Avg_Fare'] = df.groupby('Pclass')['Fare'].transform('mean')

df['Fare_Difference'] = df['Fare'] - df['Pclass_Avg_Fare']

show = df[['Name','Pclass','Fare','Pclass_Avg_Fare','Fare_Difference']].head(10)

print(show)

                                                Name  Pclass       Fare  \
0                            Braund, Mr. Owen Harris       3  13.675550   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1  84.154687   
2                             Heikkinen, Miss. Laina       3  13.675550   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  84.154687   
4                           Allen, Mr. William Henry       3  13.675550   
5                                   Moran, Mr. James       3  13.675550   
6                            McCarthy, Mr. Timothy J       1  84.154687   
7                     Palsson, Master. Gosta Leonard       3  13.675550   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       3  13.675550   
9                Nasser, Mrs. Nicholas (Adele Achem)       2  20.662183   

   Pclass_Avg_Fare  Fare_Difference  
0        13.675550              0.0  
1        84.154687              0.0  
2        13.675550              0.0  
3        84.154687    

In [9]:
#2 
"""
Create a pivot table showing the survival rate for each combination of: 
 Rows → Pclass  
 Columns → Sex  
Display the result as percentages. 
"""

pvt = df.pivot_table(
    index = 'Pclass',
    columns = 'Sex',
    values = 'Survived',
    aggfunc = 'mean'
) * 100

print(pvt)

Sex        female       male
Pclass                      
1       96.808511  36.885246
2       92.105263  15.740741
3       50.000000  13.544669


In [14]:
#3 
"""
Find passengers whose Name contains either: 
 "Mr."  
 "Dr."  
 
Display: 
Name, Sex, Age, Pclass, Survived
"""

mrd = df['Name'].str.contains('Mr.') | df['Name'].str.contains('Dr.')

show = df.loc[mrd, ['Name','Sex','Age','Pclass','Survived']]

print(show)

                                                  Name     Sex   Age  Pclass  \
0                              Braund, Mr. Owen Harris    male  22.0       3   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0       1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0       1   
4                             Allen, Mr. William Henry    male  35.0       3   
5                                     Moran, Mr. James    male   NaN       3   
..                                                 ...     ...   ...     ...   
883                      Banfield, Mr. Frederick James    male  28.0       2   
884                             Sutehall, Mr. Henry Jr    male  25.0       3   
885               Rice, Mrs. William (Margaret Norton)  female  39.0       3   
889                              Behr, Mr. Karl Howell    male  26.0       1   
890                                Dooley, Mr. Patrick    male  32.0       3   

     Survived  
0           0  
1      

In [16]:
#4 
"""
Create: 
Fare_Adjusted 
 
Rules: 
 Fare < 50 → increase by 20%  
 Fare 50–100 → increase by 10%  
 Fare > 100 → increase by 5%  
Display the 10 passengers with the highest Fare_Adjusted.
"""

df['Fare_Adjusted'] = np.where(
    df['Fare'] < 50,
    df['Fare'] * 1.20,
    
    np.where(
        (df['Fare'] >= 50) & (df['Fare'] <= 100),
        df['Fare'] * 1.10,
        df['Fare'] * 1.05
    )
)

show = df.sort_values('Fare_Adjusted', ascending=False).head(10)

print(show)

     PassengerId  Survived  Pclass  \
373          374         0       1   
435          436         1       1   
434          435         0       1   
430          431         1       1   
393          394         1       1   
390          391         1       1   
34            35         0       1   
31            32         1       1   
30            31         0       1   
27            28         0       1   

                                               Name     Sex   Age  SibSp  \
373                             Ringhini, Mr. Sante    male  22.0      0   
435                       Carter, Miss. Lucile Polk  female  14.0      1   
434                       Silvey, Mr. William Baird    male  50.0      1   
430       Bjornstrom-Steffansson, Mr. Mauritz Hakan    male  28.0      0   
393                          Newell, Miss. Marjorie  female  23.0      1   
390                      Carter, Mr. William Ernest    male  36.0      1   
34                          Meyer, Mr. Edgar Jose

In [22]:
#5 
"""
Create a separate DataFrame containing: 
Pclass 
Average_Age 
Average_Fare 
Then merge it back into the Titanic DataFrame using Pclass. 
 
Display: 
Name, Pclass, Age, Fare, Average_Age, Average_Fare 
for the first 10 passengers.
"""

summary = df.groupby('Pclass').agg(
    Average_Age=('Age', 'mean'),
    Average_Fare=('Fare', 'mean')
).reset_index()

result = df.merge(summary, on='Pclass')

show = result[['Name', 'Pclass', 'Age', 'Fare', 'Average_Age', 'Average_Fare']].head(10)

print(show)

KeyError: "['Average_Age', 'Average_Fare'] not in index"

In [26]:
#6 
"""
Create a NumPy Age array. 
Replace missing Age values with the median Age of the corresponding Pclass. 
 
Create: 
Age_Filled_By_Class 
 
Display 10 passengers who originally had missing Age: 
Name, Pclass, Age, Age_Filled_By_Class
"""

age = df['Age'].to_numpy()

df['Age_Filled_By_Class'] = df.groupby('Pclass')['Age'].transform('median')

show = df.loc[np.isnan(age),['Name','Pclass','Age','Age_Filled_By_Class']].head(10)

print(show)

                                              Name  Pclass  Age  \
5                                 Moran, Mr. James       3  NaN   
17                    Williams, Mr. Charles Eugene       2  NaN   
19                         Masselmani, Mrs. Fatima       3  NaN   
26                         Emir, Mr. Farred Chehab       3  NaN   
28                   O'Dwyer, Miss. Ellen "Nellie"       3  NaN   
29                             Todoroff, Mr. Lalio       3  NaN   
31  Spencer, Mrs. William Augustus (Marie Eugenie)       1  NaN   
32                        Glynn, Miss. Mary Agatha       3  NaN   
36                                Mamee, Mr. Hanna       3  NaN   
42                             Kraeff, Mr. Theodor       3  NaN   

    Age_Filled_By_Class  
5                  24.0  
17                 29.0  
19                 24.0  
26                 24.0  
28                 24.0  
29                 24.0  
31                 37.0  
32                 24.0  
36                 24.0  
42

In [32]:
#7 
"""
For each Sex, calculate: 
 Minimum Fare  
 Maximum Fare  
 Average Fare  
 Median Age  
 Survival Rate  
Use a single groupby().agg() operation.
"""

grp = df.groupby('Sex').agg(
                                MinFare = ('Fare','min'),
                                MaxFare = ('Fare','max'),
                                AvgFare = ('Fare','mean'),
                                MedAge = ('Age','median'),
                                SurvivalRate = ('Survived','mean')
)

print(grp)

         MinFare    MaxFare    AvgFare  MedAge  SurvivalRate
Sex                                                         
female  13.67555  84.154687  36.465432    27.0      0.742038
male    13.67555  84.154687  29.885275    29.0      0.188908


In [34]:
#8 
"""
Create: 
FamilySize = SibSp + Parch + 1 
FarePerPerson = Fare / FamilySize 
 
Then create a NumPy matrix containing: 
Pclass 
Age 
FamilySize 
Fare 
FarePerPerson 
Replace missing Age with the median Age. 
 
Print: 
1. Matrix shape  
2. First 5 rows  
"""

df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

df['FarePerPerson'] = df['Fare'] / df['FamilySize']

pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
familysize = df['FamilySize'].to_numpy()
fare = df['Fare'].to_numpy()
fareperperson = df['FarePerPerson'].to_numpy()

age = np.where(np.isnan(age), np.nanmedian(age), age)

mat = np.column_stack((pclass,age, familysize,fare,fareperperson))

print(mat.shape)

print(mat[:5])

(891, 5)
[[ 3.         22.          2.         13.6755501   6.83777505]
 [ 1.         38.          2.         84.1546875  42.07734375]
 [ 3.         26.          1.         13.6755501  13.6755501 ]
 [ 1.         35.          2.         84.1546875  42.07734375]
 [ 3.         35.          1.         13.6755501  13.6755501 ]]


In [45]:
#9 
"""
Create: 
Fare_Percent_Of_Class_Avg 
 
using: 
(Fare / Pclass_Avg_Fare) × 100 
where Pclass_Avg_Fare is created using groupby() + transform(). 
Then find the 5 passengers whose Fare is furthest above their Pclass average, using 
the largest positive percentage. 

Display: 
Name, Pclass, Fare, Pclass_Avg_Fare, Fare_Percent_Of_Class_Avg
"""

df['Pclass_Avg_Fare'] = df.groupby('Pclass')['Fare'].transform('mean')

df['Fare_Percent_Of_Class_Avg'] = (df['Fare'] / df['Pclass_Avg_Fare']) * 100

show = (
    df.sort_values('Fare_Percent_Of_Class_Avg', ascending=False)
      [['Name', 'Pclass', 'Fare','Pclass_Avg_Fare', 'Fare_Percent_Of_Class_Avg']]
      .head(5)
)

print(show)

                                                Name  Pclass       Fare  \
0                            Braund, Mr. Owen Harris       3  13.675550   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1  84.154687   
2                             Heikkinen, Miss. Laina       3  13.675550   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  84.154687   
4                           Allen, Mr. William Henry       3  13.675550   

   Pclass_Avg_Fare  Fare_Percent_Of_Class_Avg  
0        13.675550                      100.0  
1        84.154687                      100.0  
2        13.675550                      100.0  
3        84.154687                      100.0  
4        13.675550                      100.0  


In [ ]:
#10
"""
Create a final DataFrame containing: 
Survived 
Pclass 
Age 
SibSp 
Parch 
Fare 
FamilySize 
FarePerPerson 
PclassAvgFare 
FarePercentOfClassAvg 
 
Requirements: 
1. Replace missing Age with the median Age.  
2. Create FamilySize.  
3. Create FarePerPerson.  
4. Create PclassAvgFare using groupby() + transform().  
5. Create FarePercentOfClassAvg.  
6. Min-max normalize Fare.  
7. Standardize FarePerPerson.  
8. Convert the final features to a NumPy matrix.  
9. Transpose the matrix.  
10. Print the final matrix shape.
"""

age = df['Age'].to_numpy()

# 1. Replace missing Age with median
df['Age'] = np.where(np.isnan(age), np.nanmedian(age), age)

# 2. FamilySize
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

# 3. FarePerPerson
df['FarePerPerson'] = df['Fare'] / df['FamilySize']

# 4. PclassAvgFare
df['PclassAvgFare'] = (df.groupby('Pclass')['Fare'].transform('mean'))

# 5. FarePercentOfClassAvg
df['FarePercentOfClassAvg'] = (df['Fare'] / df['PclassAvgFare']) * 100

# 6. Min-max normalize Fare
fare_min = df['Fare'].min()
fare_max = df['Fare'].max()

df['Fare'] = ((df['Fare'] - fare_min) /(fare_max - fare_min))

# 7. Standardize FarePerPerson
df['FarePerPerson'] = ((df['FarePerPerson'] - df['FarePerPerson'].mean()) /df['FarePerPerson'].std())

# 8. Convert to NumPy matrix
matrix = df[
    [
        'Survived', 'Pclass', 'Age', 'SibSp', 'Parch','Fare', 'FamilySize', 'FarePerPerson',
        'PclassAvgFare', 'FarePercentOfClassAvg'
    ]
].to_numpy()

# 9. Transpose
trans = matrix.T 

# 10. Final shape
print(trans.shape)


(10, 891)
