In [6]:
#1
"""
Using NumPy, calculate: 
1. Total sales  
2. Average weekly sales  
3. Highest weekly sales  
4. Lowest weekly sales  
5. Determine whether the average weekly sales are above 15,000
"""

import numpy as np

sales = [12500, 14800, 11200, 16500, 17800, 13900, 19200, 15400] 

arr = np.array(sales)

print(f"Total sales : {arr.sum()}")
print(f"Average weekly sales : {arr.mean()}")
print(f"Highest weekly sales : {arr.max()}")
print(f"Lowest weekly sales : {arr.min()}")

if arr.mean() > 15000:
    print("Yes, average weekly sales are above 15,000")
else:
    print("No, average weekly sales are not above 15,000")



Total sales : 121300
Average weekly sales : 15162.5
Highest weekly sales : 19200
Lowest weekly sales : 11200
Yes, average weekly sales are above 15,000


In [12]:
#2
"""
Using NumPy: 
1. Find the average rating  
2. Find the highest rating  
3. Find the lowest rating  
4. Determine whether the average rating is 4.0 or higher  
5. Print a suitable conclusion. 
"""

ratings = [4.5, 3.8, 4.2, 4.9, 3.5, 4.7, 4.1, 4.8, 3.9, 4.6] 

arr = np.array(ratings)

print(f"Average rating : {arr.mean()}")
print(f"Highest rating : {arr.max()}")
print(f"Lowest rating : {arr.min()}")

if arr.mean() >= 4.0:
    print("Yes, average rating is 4.0 or higher")
else:
    print("No, average rating is not 4.0 or higher")

print(f"Conclusion : Company's performance is best as per rating")

Average rating : 4.3
Highest rating : 4.9
Lowest rating : 3.5
Yes, average rating is 4.0 or higher
Conclusion : Company's performance is best as per rating


In [18]:
#3
"""
Find: 
1. Total salary expense  
2. Average salary  
3. Highest salary  
4. Lowest salary  
5. Determine whether the average salary is above ₹35,000  
"""

salary = [28000, 35000, 42000, 31000, 50000, 39000, 45000, 33000] 

arr = np.array(salary)

print(f"Total salary expense : {arr.sum()}")
print(f"Average salary : {arr.mean()}")
print(f"Highest salary : {arr.max()}")
print(f"Lowest salary : {arr.min()}")

if arr.mean() > 35000:
    print(f"Yes, average salary is above 35000")
else:
    print(f"No, average salary is not above 35000")


Total salary expense : 303000
Average salary : 37875.0
Highest salary : 50000
Lowest salary : 28000
Yes, average salary is above 35000


In [28]:
#4
"""
Calculate: 
1. Total visitors  
2. Average daily visitors  
3. Highest daily visitors  
4. Lowest daily visitors  
5. Determine whether the website crossed 2,000 visitors on its highest-traffic day 
"""

visitors = [1250, 1480, 1320, 1890, 2100, 1750, 2250, 1980, 1600, 2350] 

arr = np.array(visitors)

print(f"Total visitors : {arr.sum()}")
print(f"Average daily visitors : {arr.mean()}")
print(f"Highest daily visitors : {arr.max()}")
print(f"Lowest daily visitors : {arr.min()}")

if arr.max() > 2000:
    print(f"Yes, website crossed 2000 visitors on its highest-traffic day")
else:
    print(f"No, website not crossed 2000 visitors on its highest-traffic day")


Total visitors : 17970
Average daily visitors : 1797.0
Highest daily visitors : 2350
Lowest daily visitors : 1250
Yes, website crossed 2000 visitors on its highest-traffic day


In [35]:
#5
"""
Using NumPy: 
1. Calculate the total price  
2. Calculate the average price  
3. Find the highest price  
4. Find the lowest price  
5. Create a new NumPy array where every price is increased by 100  
6. Print the new prices.  
"""

prices = [499, 799, 1299, 599, 1499, 999, 699, 1899] 

arr = np.array(prices)

print(f"Total price : {arr.sum()}")
print(f"Average price : {arr.mean()}")
print(f"Highest price : {arr.max()}")
print(f"Lowest price : {arr.min()}")

new = arr + 100
print(new)


Total price : 8292
Average price : 1036.5
Highest price : 1899
Lowest price : 499
[ 599  899 1399  699 1599 1099  799 1999]


In [41]:
#6
"""
Find: 
1. Total quantity ordered  
2. Average quantity per order  
3. Highest order quantity  
4. Lowest order quantity  
5. Create a NumPy array where each order quantity is doubled  
6. Determine whether the average order quantity is greater than 7  
"""

orders = [3, 7, 5, 12, 8, 15, 6, 10, 4, 9] 

arr = np.array(orders)

print(f"Total quantity ordered : {arr.sum()}")
print(f"Average quantity per order : {arr.mean()}")
print(f"Highest order quantity : {arr.max()}")
print(f"Lowest order quantity : {arr.min()}")

new = arr * 2
print(new)

if arr.mean() > 7:
    print("Yes, the average order quantity is greater than 7")
else:
    print("No, the average order quantity is not greater than 7")


Total quantity ordered : 79
Average quantity per order : 7.9
Highest order quantity : 15
Lowest order quantity : 3
[ 6 14 10 24 16 30 12 20  8 18]
Yes, the average order quantity is greater than 7


In [47]:
#7
"""
Using NumPy: 
1. Find average temperature  
2. Find maximum temperature  
3. Find minimum temperature  
4. Increase every temperature by 2°C  
5. Determine whether the highest temperature exceeded 35°C 
"""

temperature = [31, 33, 29, 35, 37, 32, 30, 36, 34, 38] 

arr = np.array(temperature)

print(f"Average temperature : {arr.mean()}")
print(f"Maximum temperature : {arr.max()}")
print(f"Minimum temperature : {arr.min()}")

new = arr + 2
print(new)

if arr.max() > 35:
    print("Yes, the highest temperature exceeded 35°C")
else:
    print("No, the highest temperature not exceeded 35°C")


Average temperature : 33.5
Maximum temperature : 38
Minimum temperature : 29
[33 35 31 37 39 34 32 38 36 40]
Yes, the highest temperature exceeded 35°C


In [ ]:
#8
"""
For both products: 
1. Calculate total revenue  
2. Calculate average revenue  
3. Find highest weekly revenue  
4. Find lowest weekly revenue  
5. Determine which product generated the higher total revenue  
"""

product_A = [12000, 14500, 13200, 15800, 17100] 
product_B = [13500, 12800, 14900, 16200, 15500]

arrA = np.array(product_A)
arrB = np.array(product_B)

print(f"Total revenue of Product_A : {arrA.sum()}")
print(f"Total revenue of Product_B : {arrB.sum()}")

print(f"Average revenue of Product_A : {arrA.mean()}")
print(f"Average revenue of Product_B : {arrB.mean()}")

print(f"Highest weekly revenue of Product_A : {arrA.max()}")
print(f"Highest weekly revenue of Product_B : {arrB.max()}")

print(f"Lowest weekly revenue of Product_A : {arrA.min()}")
print(f"Lowest weekly revenue of Product_B : {arrB.min()}")

if arrA.sum() > arrB.sum():
    print("Product_A generated the higher total revenue")
else:
    print("Product_B generated the higher total revenue")

Total revenue of Product_A : 72600
Total revenue of Product_B : 72900
Average revenue of Product_A : 14520.0
Average revenue of Product_B : 14580.0
Highest weekly revenue of Product_A : 17100
Highest weekly revenue of Product_B : 16200
Lowest weekly revenue of Product_A : 12000
Lowest weekly revenue of Product_B : 12800
Product_B generated the higher total revenue


In [62]:
#9
"""
Using NumPy: 
1. Create a NumPy array  
2. Increase every value by 50  
3. Multiply every value by 2  
4. Calculate the total of the final values  
5. Calculate the average of the final values  
6. Find the highest final value  
"""

import numpy as np

sales = [100, 200, 300, 400, 500]

arr = np.array(sales)

increase = arr + 50
final_values = increase * 2

print(f"Final values : {final_values}")
print(f"Total : {final_values.sum()}")
print(f"Average : {final_values.mean()}")
print(f"Highest value : {final_values.max()}")


Final values : [ 300  500  700  900 1100]
Total : 3500
Average : 700.0
Highest value : 1100


In [71]:
#10
"""
The company's target is: 
Average monthly sales ≥ 600 
 
Using NumPy: 
1. Calculate total sales  
2. Calculate average monthly sales  
3. Find highest monthly sales  
4. Find lowest monthly sales  
5. Increase every monthly sales value by 50  
6. Calculate the new average after the increase  
7. Determine whether the original average achieved the company target  
8. Determine whether the new average achieved the target
"""

sales = [450, 520, 680, 390, 750, 820, 610, 540, 900, 720] 

arr = np.array(sales)

print(f"Total sales : {arr.sum()}")
print(f"Average monthly sales : {arr.mean()}")
print(f"Highest monthly sales : {arr.max()}")
print(f"Lowest monthly sales : {arr.min()}")

increase = arr + 50
print(f"Incresed value : {increase}")

print(f"New average after the increase : {increase.mean()}")

if arr.mean() >= 600:
    print("Yes, the original average achieved the company target")
else:
    print("No, the original average not achieved the company target")

if increase.mean() >= 600:
    print("Yes, the new average achieved the company target")
else:
    print("No, the new average not achieved the company target")


Total sales : 6380
Average monthly sales : 638.0
Highest monthly sales : 900
Lowest monthly sales : 390
Incresed value : [500 570 730 440 800 870 660 590 950 770]
New average after the increase : 688.0
Yes, the original average achieved the company target
Yes, the new average achieved the company target
