In [3]:
#1
"""
Using NumPy: 
1. Create a NumPy array.  
2. Find total sales.  
3. Find average sales.  
4. Find highest sales.  
5. Find lowest sales.  
6. Find the last day's sales using negative indexing.  
7. Extract the first 3 days using slicing.  
8. Print shape, ndim, and dtype.  
"""

import numpy as np

sales = [12500, 14800, 13200, 17600, 15900, 19200, 18500] 

arr = np.array(sales)

print(arr)
print(f"Total sales : {arr.sum()}")
print(f"Average sales : {arr.mean()}")
print(f"Highest sales : {arr.max()}")
print(f"Lowest sales : {arr.min()}")
print(f"Last day's sales : {arr[-1]}")
print(f"First three days : {arr[:3]}")
print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"Dtype : {arr.dtype}")

[12500 14800 13200 17600 15900 19200 18500]
Total sales : 111700
Average sales : 15957.142857142857
Highest sales : 19200
Lowest sales : 12500
Last day's sales : 18500
First three days : [12500 14800 13200]
Shape : (7,)
Ndim : 1
Dtype : int64


In [4]:
#2
"""
Using NumPy: 
1. Create the array.  
2. Find average rating.  
3. Find highest and lowest rating.  
4. Extract the last 4 ratings using slicing.  
5. Extract the second rating using indexing.  
6. Check the dtype and ndim.  
7. Determine whether the average rating is ≥ 4.0.
"""

ratings = [4.2, 3.8, 4.5, 4.9, 3.7, 4.6, 4.1, 4.8] 

arr = np.array(ratings)

print(f"Average rating : {arr.mean()}")
print(f"Highest rating : {arr.max()}")
print(f"Lowest rating : {arr.min()}")
print(f"Last 4 ratings : {arr[-4:]}")
print(f"Second ratings : {arr[1]}")
print(f"dtype : {arr.dtype}")
print(f"ndim : {arr.ndim}")

if arr.mean() >= 4.0:
    print(f"Yes, the average rating is >= 4.0")
else:
    print(f"No, the average rating is not >= 4.0")

Average rating : 4.324999999999999
Highest rating : 4.9
Lowest rating : 3.7
Last 4 ratings : [3.7 4.6 4.1 4.8]
Second ratings : 3.8
dtype : float64
ndim : 1
Yes, the average rating is >= 4.0


In [5]:
#3
"""
Using NumPy: 
1. Create a 2D array.  
2. Print its shape and ndim.  
3. Find the salary of the second employee in the third department.  
4. Extract the complete second row.  
5. Extract the first two columns.  
6. Find the highest salary in the entire array.  
7. Find the lowest salary in the entire array. 
"""

salary = [ 
    [28000, 35000, 42000], 
    [31000, 45000, 39000], 
    [50000, 33000, 47000] 
] 

arr = np.array(salary)

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"Salary of the second employee in the third department : {arr[1][2]}")
print(f"Complete second row : {arr[1]}")
print(f"first two columns : {arr[:, :2]}")
print(f"Highest salary : {arr.max()}")
print(f"Lowest salary : {arr.min()}")

Shape : (3, 3)
Ndim : 2
Salary of the second employee in the third department : 39000
Complete second row : [31000 45000 39000]
first two columns : [[28000 35000]
 [31000 45000]
 [50000 33000]]
Highest salary : 50000
Lowest salary : 28000


In [6]:
#4
"""
Using NumPy: 
1. Create the 2D array.  
2. Find total sales of the South region.  
3. Find the sales of the last month for West.  
4. Extract the first 2 months for all regions.  
5. Extract the last 2 months for North.  
6. Find the highest sales value.  
7. Print shape and ndim. 

Rows represent North, South, West and columns represent four months. 
"""

sales = [ 
    [120, 150, 180, 200], 
    [140, 160, 190, 220], 
    [110, 135, 175, 210] 
]

arr = np.array(sales)

print(f"Total sales of the South region : {arr[1].sum()}")
print(f"The sales of the last month for West : {arr[2,-1]}")
print(f"The first 2 months for all regions : {arr[:, :2]}")
print(f"The last 2 months for North : {arr[0,-2:]}")
print(f"The highest sales value : {arr.max()}")
print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")

Total sales of the South region : 710
The sales of the last month for West : 210
The first 2 months for all regions : [[120 150]
 [140 160]
 [110 135]]
The last 2 months for North : [180 200]
The highest sales value : 220
Shape : (3, 4)
Ndim : 2


In [7]:
#5
"""
Using NumPy: 
1. Create the array.  
2. Increase every price by ₹100.  
3. Find the new average price.  
4. Find the highest new price.  
5. Extract the first 4 new prices.  
6. Find the last price using negative indexing.  
7. Print the datatype of the array.  
"""

prices = [499, 799, 999, 1299, 1499, 1799] 

arr = np.array(prices)

new = arr + 100

print(f"Increased price : {new}")
print(f"Average price : {new.mean()}")
print(f"Highest price : {new.max()}")
print(f"the first 4 new prices : {new[:4]}")
print(f"last price using negative indexing : {new[-1]}")
print(f"the datatype of the array : {new.dtype}")

Increased price : [ 599  899 1099 1399 1599 1899]
Average price : 1249.0
Highest price : 1899
the first 4 new prices : [ 599  899 1099 1399]
last price using negative indexing : 1899
the datatype of the array : int64


In [8]:
#6
"""
Using NumPy: 
1. Create the array.  
2. Add 2 to every temperature.  
3. Find the average of the updated temperatures.  
4. Find the highest updated temperature.  
5. Extract values from index 2 to index 7.  
6. Find the second-last temperature using negative indexing.  
7. Determine whether the updated maximum temperature is above 37.  
"""

temperature = [28, 30, 31, 29, 32, 35, 33, 36, 34, 30] 

arr = np.array(temperature)

new = arr + 2

print(new)
print(f"Average of the updated temperatures : {new.mean()}")
print(f"highest updated temperature : {new.max()}")
print(f"values from index 2 to index 7 : {new[2:8]}")
print(f"second-last temperature using negative indexing : {new[-2]}")

if new.max() > 37:
    print("Yes, the updated maximum temperature is above 37")
else:
    print("No, the updated maximum temperature is not above 37")


[30 32 33 31 34 37 35 38 36 32]
Average of the updated temperatures : 33.8
highest updated temperature : 38
values from index 2 to index 7 : [33 31 34 37 35 38]
second-last temperature using negative indexing : 36
Yes, the updated maximum temperature is above 37


In [9]:
#7
"""
Using NumPy: 
1. Create the 3D array.  
2. Print its shape.  
3. Print its ndim.  
4. Find the sales value of Region 2 → Product 3 → Month 4.  
5. Extract all monthly sales of Region 1 → Product 2.  
6. Find the highest value in the entire array.  
7. Find the lowest value in the entire array.  
"""

sales = [ 
    [ 
        [100, 120, 140, 160], 
        [200, 220, 240, 260], 
        [300, 320, 340, 360] 
    ], 
    [ 
        [150, 170, 190, 210], 
        [250, 270, 290, 310], 
        [350, 370, 390, 410] 
    ] 
]

arr = np.array(sales)

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"Sales value of Region 2 → Product 3 → Month 4 : {arr[1][2][3]}")
print(f"All monthly sales of Region 1 → Product 2 : {arr[0][1]}")
print(f"Highest value in the entire array : {arr.max()}")
print(f"Lowest value in the entire array : {arr.min()}")

Shape : (2, 3, 4)
Ndim : 3
Sales value of Region 2 → Product 3 → Month 4 : 410
All monthly sales of Region 1 → Product 2 : [200 220 240 260]
Highest value in the entire array : 410
Lowest value in the entire array : 100


In [10]:
#8
"""
Create the following arrays using NumPy: 
1. A 3 × 4 array containing only zeros using zeros().  
2. A 2 × 5 array containing only ones using ones().  
3. A 3 × 3 array where every value is 100 using full().  
4. Create a 2 × 3 array using empty().  
5. Print the shape and ndim of each array.  
"""

print("Zeros :")
print(np.zeros([3,4]))
print(f"Shape : {np.zeros([3,4]).shape}")
print(f"Ndim : {np.zeros([3,4]).ndim}")
print()

print("Ones :")
print(np.ones([2,5]))
print(f"Shape : {np.ones([2,5]).shape}")
print(f"Ndim : {np.ones([2,5]).ndim}")
print()

print("Full :")
print(np.full((3,3),100))
print(f"Shape : {np.full((3,3),100).shape}")
print(f"Ndim : {np.full((3,3),100).ndim}")
print()

print("Empty")
print(np.empty([2,3]))
print(f"Shape : {np.empty([2,3]).shape}")
print(f"Ndim : {np.empty([2,3]).ndim}")
print()

Zeros :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape : (3, 4)
Ndim : 2

Ones :
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape : (2, 5)
Ndim : 2

Full :
[[100 100 100]
 [100 100 100]
 [100 100 100]]
Shape : (3, 3)
Ndim : 2

Empty
[[2.96e-321 4.44e-321 5.43e-321]
 [6.91e-321 7.90e-321 9.38e-321]]
Shape : (2, 3)
Ndim : 2



In [11]:
#9
"""
Using NumPy: 
1. Create an integer array for sales.  
2. Create a floating-point array for ratings.  
3. Print the dtype of both arrays.  
4. Convert the sales array into float.  
5. Print the new datatype.  
6. Calculate the average of both arrays. 
"""

sales = [100, 200, 300, 400] 
ratings = [4.2, 4.5, 3.8, 4.9]

sales_arr = np.array(sales)
ratings_arr = np.array(ratings)

Converted = sales_arr.astype(float)

print(f"dtype of sales_arr : {sales_arr.dtype}")
print(f"dtype of ratings_arr : {ratings_arr.dtype}")
print(f"Converted : {Converted}")
print(f"New datatypes : {Converted.dtype}")

print(f"Average of sales_arr : {sales_arr.mean()}")
print(f"Average of ratings_arr : {ratings_arr.mean()}")

dtype of sales_arr : int64
dtype of ratings_arr : float64
Converted : [100. 200. 300. 400.]
New datatypes : float64
Average of sales_arr : 250.0
Average of ratings_arr : 4.35


In [37]:
#10
"""
Using NumPy: 
1. Create the 2D array.  
2. Print shape, ndim, and dtype.  
3. Find the total annual sales of Product B.  
4. Find the Q4 sales of Product C using indexing.  
5. Extract Q1 and Q2 sales for all products using slicing.  
6. Find the highest quarterly sales in the entire dataset.  
7. Increase all sales by 10%.  
8. Find the new highest sales value after the increase.  
9. Determine which product has the highest original annual sales.

Rows = Products A, B, C 
Columns = Q1, Q2, Q3, Q4
"""

sales = [ 
    [12000, 15000, 18000, 21000], 
    [14000, 16000, 19000, 23000], 
    [11000, 17000, 20000, 25000] 
]

arr = np.array(sales)

increased = arr + (arr * 10) / 100

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"Dtype : {arr.dtype}")
print(f"The total annual sales of product B : {arr[1].sum()}")
print(f"Q4 sales of Product C using indexing : {arr[2][-1]}")
print(f"Q1 and Q2 sales for all products using slicing : {arr[:,:2]}")
print(f"the highest quarterly sales in the entire dataset : {arr.max()}")
print(f"all sales by 10% : {increased}")
print(f"highest sales value after the increase : {increased.max()}")

annual_sales = arr.sum(axis=1)

print(annual_sales)
print(np.argmax(annual_sales))


Shape : (3, 4)
Ndim : 2
Dtype : int64
The total annual sales of product B : 72000
Q4 sales of Product C using indexing : 25000
Q1 and Q2 sales for all products using slicing : [[12000 15000]
 [14000 16000]
 [11000 17000]]
the highest quarterly sales in the entire dataset : 25000
all sales by 10% : [[13200. 16500. 19800. 23100.]
 [15400. 17600. 20900. 25300.]
 [12100. 18700. 22000. 27500.]]
highest sales value after the increase : 27500.0
[66000 72000 73000]
2
