In [2]:
import numpy as np

In [10]:
#1
"""
Using NumPy: 
1. Create the array.  
2. Find total sales.  
3. Find average sales.  
4. Find the highest and lowest sales.  
5. Extract sales of the first 4 days.  
6. Extract sales of the last 3 days.  
7. Check whether the highest sales are greater than 20000.  
8. Print shape and ndim.  
"""

sales = [12500, 14800, 13200, 17600, 15900, 19200, 18500, 21000] 

arr = np.array(sales)

print(f"Total sales : {arr.sum()}")
print(f"Average sales : {arr.mean()}")
print(f"Highest sales : {arr.max()}")
print(f"Lowest sales : {arr.min()}")
print(f"Sales of the first 4 days : {arr[:4]}")
print(f"Sales of the last 3 days : {arr[-3:]}")

if arr.max() > 20000:
    print("Yes, the highest sales are greater than 20000")
else:
    print("No, the highest sales are not greater than 20000")

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")

Total sales : 132700
Average sales : 16587.5
Highest sales : 21000
Lowest sales : 12500
Sales of the first 4 days : [12500 14800 13200 17600]
Sales of the last 3 days : [19200 18500 21000]
Yes, the highest sales are greater than 20000
Shape : (8,)
Ndim : 1


In [19]:
#2
"""
Using NumPy: 
1. Create the array.  
2. Find average rating.  
3. Find highest and lowest rating.  
4. Extract ratings from the 3rd to 7th customer.  
5. Extract the last 3 ratings.  
6. Find the rating of the 5th customer.  
7. Check whether average rating is at least 4.0.  
8. Print dtype.  
"""

ratings = [4.1, 3.8, 4.5, 4.7, 3.9, 4.8, 4.2, 4.6, 3.7] 

arr = np.array(ratings)

print(f"Average rating : {arr.mean()}")
print(f"Highest rating : {arr.max()}")
print(f"Lowest rating : {arr.min()}")
print(f"ratings from the 3rd to 7th customer : {arr[2:7]}")
print(f"the last 3 ratings : {arr[-3:]}")
print(f"the rating of the 5th customer : {arr[4]}")

if arr.mean() >= 4.0:
    print(f"Yes, average rating is at least 4.0")
else:
    print(f"No, average rating is not at least 4.0")

print(f"Dtype : {arr.dtype}")


Average rating : 4.2555555555555555
Highest rating : 4.8
Lowest rating : 3.7
ratings from the 3rd to 7th customer : [4.5 4.7 3.9 4.8 4.2]
the last 3 ratings : [4.2 4.6 3.7]
the rating of the 5th customer : 3.9
Yes, average rating is at least 4.0
Dtype : float64


In [30]:
#3
"""
Using NumPy: 
1. Create the 2D array.  
2. Print shape and ndim.  
3. Find the salary of Employee 3 in February.  
4. Extract the complete salary record of Employee 2.  
5. Extract January and February salaries of all employees.  
6. Find the highest salary.  
7. Find the lowest salary.  
8. Find the total salary of Employee 4.  

Rows = Employees 
Columns = Jan, Feb, Mar
"""

salary = [ 
    [28000, 30000, 32000], 
    [35000, 37000, 39000], 
    [42000, 44000, 46000], 
    [31000, 33000, 35000] 
] 

arr = np.array(salary)

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"the salary of Employee 3 in February : {arr[2][1]}")
print(f"the complete salary record of Employee 2 : {arr[1]}")
print(f"January and February salaries of all employees : {arr[:,:2]}")
print(f"January and February salaries of all employees : {arr[:,:2]}")
print(f"Highest salary : {arr.max()}")
print(f"Lowest salary : {arr.min()}")
print(f"total salary of Employee 4 : {arr.sum(axis=1)[-1]}")

Shape : (4, 3)
Ndim : 2
the salary of Employee 3 in February : 44000
the complete salary record of Employee 2 : [35000 37000 39000]
January and February salaries of all employees : [[28000 30000]
 [35000 37000]
 [42000 44000]
 [31000 33000]]
January and February salaries of all employees : [[28000 30000]
 [35000 37000]
 [42000 44000]
 [31000 33000]]
Highest salary : 46000
Lowest salary : 28000
total salary of Employee 4 : 99000


In [38]:
#4
"""
Using NumPy: 
1. Create the 2D array.  
2. Find total annual sales of North.  
3. Find total annual sales of West.  
4. Extract Q3 and Q4 sales of all regions.  
5. Find the Q2 sales of South.  
6. Find the highest quarterly sales.  
7. Find the lowest quarterly sales.  
8. Print shape and ndim. 

Rows = North, South, West 
Columns = Q1, Q2, Q3, Q4
"""

sales = [ 
    [12000, 15000, 18000, 21000], 
    [14000, 16000, 19000, 23000], 
    [11000, 17000, 20000, 25000] 
]

arr = np.array(sales)

print(f"total annual sales of North : {arr.sum(axis=1)[0]}")
print(f"total annual sales of West : {arr.sum(axis=1)[-1]}")
print(f"Q3 and Q4 sales of all regions : {arr[:,-2:]}")
print(f"Q2 sales of South : {arr[1][1]}")
print(f"highest quarterly sales : {arr.max()}")
print(f"lowest quarterly sales : {arr.min()}")
print(f"shape : {arr.shape}")
print(f"ndim : {arr.ndim}")

total annual sales of North : 66000
total annual sales of West : 73000
Q3 and Q4 sales of all regions : [[18000 21000]
 [19000 23000]
 [20000 25000]]
Q2 sales of South : 16000
highest quarterly sales : 25000
lowest quarterly sales : 11000
shape : (3, 4)
ndim : 2


In [45]:
#5
"""
Using NumPy: 
1. Create the array.  
2. Increase every price by ₹150.  
3. Find the average of the new prices.  
4. Find the highest new price.  
5. Extract the first 5 new prices.  
6. Extract the last 2 new prices.  
7. Check whether the highest new price is greater than ₹2000. 
"""

prices = [499, 799, 999, 1299, 1499, 1799, 1999] 

arr = np.array(prices)

new = arr + 150

print(f"average of the new prices : {new.mean()}")
print(f"highest new price : {new.max()}")
print(f"first 5 new prices : {new[:5]}")
print(f"last 2 new prices : {new[-2:]}")

if new.max() > 2000:
    print("Yes, the highest new price is greater than ₹2000")
else:
    print("No, the highest new price is not greater than ₹2000")


average of the new prices : 1420.4285714285713
highest new price : 2149
first 5 new prices : [ 649  949 1149 1449 1649]
last 2 new prices : [1949 2149]
Yes, the highest new price is greater than ₹2000


In [55]:
#6
"""
Using NumPy: 
1. Create the array.  
2. Increase every temperature by 2°C.  
3. Find the average temperature after the increase.  
4. Find the highest temperature after the increase.  
5. Extract values from index 3 to 8.  
6. Extract the last 4 values.  
7. Check whether any recorded temperature after increase is greater than 38°C. 
"""

temperature = [27, 29, 31, 30, 33, 35, 34, 37, 36, 32, 31, 30] 

arr = np.array(temperature)

new = arr + 2

print(new)
print(f"average temperature after the increase : {new.mean()}")
print(f"highest temperature after the increase : {new.max()}")
print(f"values from index 3 to 8 : {new[3:9]}")
print(f"last 4 values : {new[-4:]}")

if (new > 38).any():
    print("Yes, recorded temperature after increase is greater than 38°C")
else:
    print("No, recorded temperature after increase is greater than 38°C")


[29 31 33 32 35 37 36 39 38 34 33 32]
average temperature after the increase : 34.083333333333336
highest temperature after the increase : 39
values from index 3 to 8 : [32 35 37 36 39 38]
last 4 values : [38 34 33 32]
Yes, recorded temperature after increase is greater than 38°C


In [62]:
#7
"""
Using NumPy: 
1. Create the 3D array.  
2. Print shape and ndim.  
3. Find Region 2 → Product 3 → Month 2.  
4. Extract all months of Region 1 → Product 2.  
5. Extract all products of Region 2 → Month 3.  
6. Find the maximum inventory value.  
7. Find the minimum inventory value. 

Dimensions: 
Region → Product → Month 
"""

inventory = [ 
    [ 
        [100, 120, 140], 
        [200, 220, 240], 
        [300, 320, 340] 
    ], 
    [ 
        [150, 170, 190], 
        [250, 270, 290], 
        [350, 370, 390] 
    ] 
] 

arr = np.array(inventory)

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"Region 2 → Product 3 → Month 2 : {arr[1][2][1]}")
print(f"all months of Region 1 → Product 2 : {arr[0][1]}")
print(f"all products of Region 2 → Month 3 : {arr[1][:,-1]}")
print(f"maximum inventory value : {arr.max()}")
print(f"minimum inventory value : {arr.min()}")

Shape : (2, 3, 3)
Ndim : 3
Region 2 → Product 3 → Month 2 : 370
all months of Region 1 → Product 2 : [200 220 240]
all products of Region 2 → Month 3 : [190 290 390]
maximum inventory value : 390
minimum inventory value : 100


In [79]:
#8
"""
Create the following arrays: 
1. 4 × 3 zeros.  
2. 3 × 4 ones.  
3. 2 × 5 array filled with 50.  
4. 3 × 3 array filled with 999.  
5. 2 × 4 empty array.  
Then print the shape and ndim of every array.
"""

zeros = np.zeros([4,3])
print("Zeros :-")
print(zeros)
print(f"Shape : {zeros.shape}")
print(f"Ndim : {zeros.ndim}")
print()

ones = np.ones([3,4])
print("Ones :-")
print(ones)
print(f"Shape : {ones.shape}")
print(f"Ndim : {ones.ndim}")
print()

Full = np.full((2,5),50)
print("Full :-")
print(Full)
print(f"Shape : {Full.shape}")
print(f"Ndim : {Full.ndim}")
print()

full = np.full((3,3),999)
print("Full :-")
print(full)
print(f"Shape : {full.shape}")
print(f"Ndim : {full.ndim}")
print()

empty = np.empty([2,4])
print("Emptry :-")
print(empty)
print(f"Shape : {empty.shape}")
print(f"Ndim : {empty.ndim}")
print()

Zeros :-
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape : (4, 3)
Ndim : 2

Ones :-
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape : (3, 4)
Ndim : 2

Full :-
[[50 50 50 50 50]
 [50 50 50 50 50]]
Shape : (2, 5)
Ndim : 2

Full :-
[[999 999 999]
 [999 999 999]
 [999 999 999]]
Shape : (3, 3)
Ndim : 2

Emptry :-
[[6.17582e-320 7.31217e-320 6.52167e-320 8.69556e-320]
 [7.85564e-320 9.48606e-320 9.14021e-320 1.03754e-319]]
Shape : (2, 4)
Ndim : 2



In [90]:
#9
"""
Using NumPy: 
1. Create both arrays.  
2. Print their dtypes.  
3. Convert sales into float.  
4. Print the converted array and its dtype.  
5. Find average sales.  
6. Find average rating.  
7. Print shape and ndim of both arrays. 
"""

sales = [1000, 1500, 2000, 2500] 
ratings = [4.2, 4.5, 3.9, 4.8] 

sales_arr = np.array(sales)
ratings_arr = np.array(ratings)

print(f"Sales_arr datatypes : {sales_arr.dtype}")
print(f"Ratings_arr datatypes : {ratings_arr.dtype}")
print(f"Converted : {sales_arr.astype(float)}")
print(f"Converted type : {sales_arr.astype(float).dtype}")
print(f"average sales : {sales_arr.mean()}")
print(f"average ratings : {ratings_arr.mean()}")
print(f"shape of sales : {sales_arr.shape}")
print(f"shape of ratings : {ratings_arr.shape}")
print(f"ndim of sales : {sales_arr.ndim}")
print(f"ndim of ratings : {ratings_arr.ndim}")

Sales_arr datatypes : int64
Ratings_arr datatypes : float64
Converted : [1000. 1500. 2000. 2500.]
Converted type : float64
average sales : 1750.0
average ratings : 4.35
shape of sales : (4,)
shape of ratings : (4,)
ndim of sales : 1
ndim of ratings : 1


In [ ]:
#10
"""
Using NumPy: 
1. Create the 2D array.  
2. Print shape, ndim, and dtype.  
3. Find annual sales of each product.  
4. Determine which product has the highest annual sales.  
5. Find Q4 sales of Product B.  
6. Extract Q1 and Q2 sales of all products.  
7. Find the highest quarterly sales.  
8. Increase all sales by 15%.  
9. Find the new highest quarterly sales.  
10. Check whether the new highest sales exceed ₹30,000.

Rows = Products A, B, C 
Columns = Q1, Q2, Q3, Q4 
"""

sales = [ 
    [15000, 18000, 21000, 24000], 
    [17000, 19000, 23000, 26000], 
    [14000, 20000, 25000, 28000] 
] 

arr = np.array(sales)

new = arr + (arr * 15) / 100

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"Dtype : {arr.dtype}")
print(f"annual sales of each product : {arr.sum(axis=1)}")
print(f"highest annual sales : {arr.sum(axis=1)}")
print(f"Q4 sales of Product B : {arr[1][-1]}")
print(f"Q1 and Q2 sales of all products : {arr[:,:2]}")
print(f"highest quarterly sales : {arr.max()}")
print(f"Increased : {new}")
print(f"new highest quarterly sales : {new.max()}")

if new.max() > 30000:
    print("Yes, the new highest sales exceed ₹30,000")
else:
    print("No, the new highest sales doesn't exceed ₹30,000")


Shape : (3, 4)
Ndim : 2
Dtype : int64
annual sales of each product : [78000 85000 87000]
highest annual sales : [78000 85000 87000]
Q4 sales of Product B : 26000
Q1 and Q2 sales of all products : [[15000 18000]
 [17000 19000]
 [14000 20000]]
highest quarterly sales : 28000
Increased : [[16500. 19800. 23100. 26400.]
 [18700. 20900. 25300. 28600.]
 [15400. 22000. 27500. 30800.]]
new highest quarterly sales : 30800.0
Yes, the new highest sales exceed ₹30,000
