In [2]:
import numpy as np

In [3]:
#1
"""
Perform: 
1. Create the NumPy array.  
2. Find total visitors.  
3. Find average visitors per hour.  
4. Find the busiest hour's visitor count.  
5. Extract visitors from hour 4 to hour 9.  
6. Extract the last 4 hours.  
7. Increase every value by 10% to simulate projected traffic.  
8. Find the maximum projected traffic.  
9. Check whether projected traffic crosses 330.  
10. Print shape and ndim. 
"""

visitors = [120, 145, 132, 178, 210, 195, 230, 260, 245, 280, 310, 295] 

arr = np.array(visitors)

increased = arr + (arr * 10) / 100

print(f"total visitors : {arr.sum()}")
print(f"average visitors : {arr.mean()}")
print(f"the busiest hour's visitor count : {arr.max()}")
print(f"visitors from hour 4 to hour 9 : {arr[3:9]}")
print(f"the last 4 hours : {arr[-4:]}")
print(f"maximum projected traffic : {increased.max()}")

if (increased > 330).any():
    print("Yes, projected traffic crosses 330")
else:
    print("No, projected traffic doesn't crosses 330")

print(f"Shape : {increased.shape}")
print(f"Ndim : {increased.ndim}")


total visitors : 2600
average visitors : 216.66666666666666
the busiest hour's visitor count : 310
visitors from hour 4 to hour 9 : [178 210 195 230 260 245]
the last 4 hours : [245 280 310 295]
maximum projected traffic : 341.0
Yes, projected traffic crosses 330
Shape : (12,)
Ndim : 1


In [4]:
#2
"""
Find: 
1. Average delivery time.  
2. Fastest delivery.  
3. Slowest delivery.  
4. Extract the first 5 orders.  
5. Extract the last 3 orders.  
6. Extract orders 3–7.  
7. Add 5 minutes to every delivery time as a simulated traffic delay.  
8. Find the new average.  
9. Find the new maximum.  
10. Check whether the delayed maximum exceeds 60 minutes. 
"""

delivery_time = [32, 45, 28, 51, 39, 42, 55, 31, 48, 36] 

arr = np.array(delivery_time)

new = arr + 5

print(f"Average delivery time : {arr.mean()}")
print(f"Fastest delivery time : {arr.min()}")
print(f"Slowest delivery time : {arr.max()}")
print(f"the first 5 orders : {arr[:5]}")
print(f"the last 3 orders : {arr[-3:]}")
print(f"orders 3–7 : {arr[2:7]}")
print(f"new average. : {new.mean()}")
print(f"new maximum. : {new.max()}")

if (new > 60).any():
    print("Yes, the delayed maximum exceeds 60 minutes")
else:
    print("No, the delayed maximum not exceeds 60 minutes")


Average delivery time : 40.7
Fastest delivery time : 28
Slowest delivery time : 55
the first 5 orders : [32 45 28 51 39]
the last 3 orders : [31 48 36]
orders 3–7 : [28 51 39 42 55]
new average. : 45.7
new maximum. : 60
No, the delayed maximum not exceeds 60 minutes


In [ ]:
#3
"""
Tasks: 
1. Create the 2D array.  
2. Find total annual expense of each department.  
3. Find the overall average expense.  
4. Find the maximum expense.  
5. Find the minimum expense.  
6. Extract Feb and Mar expenses for all departments.  
7. Extract all months of Department 2.  
8. Find the total expense of each department using axis=1.  
9. Check whether any monthly expense exceeds ₹50,000. 

Rows = Departments 
Columns = Jan, Feb, Mar, Apr 
"""

expenses = [ 
[45000, 47000, 49000, 51000], 
[32000, 35000, 34000, 38000], 
[28000, 30000, 31000, 33000] 
] 

arr = np.array(expenses)

print(f"total annual expense of each department : {arr.sum(axis=1)}")
print(f"the overall average expense : {arr.mean()}")
print(f"the maximum expense : {arr.max()}")
print(f"the minimum expense : {arr.min()}")
print(f"Feb and Mar expenses for all departments : {arr[:,1:3]}")
print(f"all months of Department 2 : {arr[1]}")
print(f"total expense of each department using axis=1 : {arr.sum(axis=1)}")

if (arr > 50000).any():
    print("Yes, monthly expense exceeds ₹50,000")
else:
    print("No, monthly expense not exceeds ₹50,000")

total annual expense of each department : [192000 139000 122000]
the overall average expense : 37750.0
the maximum expense : 51000
the minimum expense : 28000
Feb and Mar expenses for all departments : [[47000 49000]
 [35000 34000]
 [30000 31000]]
all months of Department 2 : [32000 35000 34000 38000]
total expense of each department using axis=1 : [192000 139000 122000]
Yes, monthly expense exceeds ₹50,000


In [ ]:
#4
"""
Find: 
1. Create both arrays.  
2. Average conversions for A.  
3. Average conversions for B.  
4. Maximum conversion for A.  
5. Maximum conversion for B.  
6. Combine the two arrays into a 2D array.  
7. Print its shape and ndim.  
8. Find the total conversions for each version using axis=1.  
9. Increase Version B conversions by 10%.  
10. Find the new average of Version B. 
"""

A = [42, 48, 51, 46, 55, 60, 58] 
B = [45, 52, 49, 57, 61, 64, 68] 

arr_A = np.array(A)
arr_B = np.array(B)

print(f"Average conversions for A : {arr_A.mean()}")
print(f"Average conversions for B : {arr_B.mean()}")

print(f"Maximum conversions for A : {arr_A.max()}")
print(f"Maximum conversions for B : {arr_B.max()}")

combine = np.array([A,B])
print(f"Combine array : {combine}")

print(f"Shape : {combine.shape}")
print(f"Ndim : {combine.ndim}")

print(f"total conversions for each version : {combine.sum(axis=1)}")

increased = arr_B + (arr_B * 10) / 100
print(f"Increased version of B : {increased}")

print(f"new average of Version B : {increased.mean()}")

Average conversions for A : 51.42857142857143
Average conversions for B : 56.57142857142857
Maximum conversions for A : 60
Maximum conversions for B : 68
Combine array : [[42 48 51 46 55 60 58]
 [45 52 49 57 61 64 68]]
Shape : (2, 7)
Ndim : 2
total conversions for each version : [360 396]
Increased version of B : [49.5 57.2 53.9 62.7 67.1 70.4 74.8]
new average of Version B : 62.22857142857142


In [27]:
#5
"""
Find: 
1. Create the array.  
2. Add 20 units to every product.  
3. Find the new inventory.  
4. Find average inventory.  
5. Find maximum and minimum inventory.  
6. Extract products 2–6.  
7. Extract the last 3 products.  
8. Check whether the minimum inventory is below 30.  
9. Print shape and ndim.  

A store has inventory for 8 products: 
The store receives 20 additional units for every product. 
"""

inventory = [45, 12, 78, 23, 8, 56, 15, 92] 

arr = np.array(inventory)

add = arr + 20

print(f"new inventory : {add}")
print(f"average inventory : {add.mean()}")
print(f"maximum inventory : {add.max()}")
print(f"minimum inventory : {add.min()}")
print(f"products 2–6 : {add[1:6]}")
print(f"last 3 products : {add[-3:]}")

if add.min() < 30:
    print("Yes, the minimum inventory is below 30")
else:
    print("No, the minimum inventory is not below 30")

print(f"Shape : {add.shape}")
print(f"Ndim : {add.ndim}")


new inventory : [ 65  32  98  43  28  76  35 112]
average inventory : 61.125
maximum inventory : 112
minimum inventory : 28
products 2–6 : [32 98 43 28 76]
last 3 products : [ 76  35 112]
Yes, the minimum inventory is below 30
Shape : (8,)
Ndim : 1


In [52]:
#6
"""
Find: 
1. Shape and ndim.  
2. Marks of Student 4 in Python.  
3. All subjects of Student 2.  
4. Maths and Statistics marks of all students.  
5. Total marks of every student using axis=1.  
6. Average marks of every student using axis=1.  
7. Highest individual mark.  
8. Lowest individual mark.  
9. Add 5 marks to every student's Python score only.  
10. Print the updated matrix. 

Rows = Students 
Columns = Maths, Statistics, Python 
"""

marks = [ 
[72, 68, 81], 
[85, 78, 90], 
[64, 71, 69], 
[91, 88, 94], 
[76, 82, 79] 
]

arr = np.array(marks)

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"Marks of Student 4 in Python : {arr[3][-1]}")
print(f"All subjects of Student 2 : {arr[1]}")
print(f"Maths and Statistics marks of all students : {arr[:,:2]}")
print(f"Total marks of every student : {arr.sum(axis=1)}")
print(f"Average marks of every student : {arr.mean(axis=1)}")
print(f"Highest individual mark : {arr.max(axis=1)}")
print(f"Lowest individual mark : {arr.min(axis=1)}")

arr[:,-1] = arr[:,-1] + 5
print(f"updated matrix : {arr}")

Shape : (5, 3)
Ndim : 2
Marks of Student 4 in Python : 94
All subjects of Student 2 : [85 78 90]
Maths and Statistics marks of all students : [[72 68]
 [85 78]
 [64 71]
 [91 88]
 [76 82]]
Total marks of every student : [221 253 204 273 237]
Average marks of every student : [73.66666667 84.33333333 68.         91.         79.        ]
Highest individual mark : [81 90 71 94 82]
Lowest individual mark : [68 78 64 88 76]
updated matrix : [[72 68 86]
 [85 78 95]
 [64 71 74]
 [91 88 99]
 [76 82 84]]


In [63]:
#7
"""
Find: 
1. Shape and ndim.  
2. Store 2 → Product 1 → Quarter 3.  
3. All quarters of Store 1 → Product 2.  
4. All products of Store 3 → Quarter 4.  
5. Maximum sales value.  
6. Minimum sales value.  
7. Extract all products and quarters of Store 2.  
8. Find total sales of Store 1.  
9. Check whether maximum sales exceed ₹24,000.  

Dimensions: 
Store → Product → Quarter 
"""

sales = [ 
    [ 
        [12000, 15000, 18000, 21000], 
        [10000, 13000, 16000, 19000] 
    ], 
    [ 
        [14000, 17000, 20000, 23000], 
        [11000, 15000, 18000, 22000] 
    ], 
    [ 
        [16000, 19000, 22000, 25000], 
        [13000, 16000, 21000, 24000] 
    ] 
]

arr = np.array(sales)

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"Store 2 → Product 1 → Quarter 3 : {arr[1][0][2]}")
print(f"All quarters of Store 1 → Product 2 : {arr[0][1]}")
print(f"All products of Store 3 → Quarter 4 : {arr[2][:,-1]}")
print(f"Maximum sales value : {arr.max()}")
print(f"Minimum sales value : {arr.min()}")
print(f"all products and quarters of Store 2 : {arr[1]}")
print(f"total sales of Store 1 : {arr[0].sum()}")

if arr.max() > 24000:
    print("Yes, maximum sales exceed ₹24,000")
else:
    print("No, maximum sales not exceed ₹24,000")


Shape : (3, 2, 4)
Ndim : 3
Store 2 → Product 1 → Quarter 3 : 20000
All quarters of Store 1 → Product 2 : [10000 13000 16000 19000]
All products of Store 3 → Quarter 4 : [25000 24000]
Maximum sales value : 25000
Minimum sales value : 10000
all products and quarters of Store 2 : [[14000 17000 20000 23000]
 [11000 15000 18000 22000]]
total sales of Store 1 : 124000
Yes, maximum sales exceed ₹24,000


In [ ]:
#8
"""
Using only your learned NumPy concepts: 
1. Create the array.  
2. Find the total recorded amount.  
3. Find the average including zeros.  
4. Extract the non-zero values manually using slicing/indexing.  
5. Calculate the average of those recorded values.  
6. Find maximum recorded transaction.  
7. Find minimum recorded transaction.  
8. Create a new array by adding ₹100 to the recorded transaction values.  
9. Find the new average. 

Here 0 represents a transaction that was not recorded. 
"""

transactions = [1200, 1500, 0, 1800, 0, 2200, 1950, 0, 2500] 

arr = np.array(transactions)

print(f"total recorded amount : {arr.sum()}")
print(f"average recorded amount : {arr.mean()}")

non_zero = arr[[0, 1, 3, 5, 6, 8]]
print(f"non-zero values : {non_zero}")

print(f"average of those recorded values : {non_zero.mean()}")

print(f"maximum recorded transaction : {non_zero.max()}")
print(f"minimum recorded transaction : {non_zero.min()}")

new = non_zero + 100
print(f"new array : {new}")

print(f"new average : {new.mean()}")

total recorded amount : 11150
average recorded amount : 1238.888888888889
non-zero values : [1200 1500 1800 2200 1950 2500]
average of those recorded values : 1858.3333333333333
maximum recorded transaction : 2500
minimum recorded transaction : 1200
new array : [1300 1600 1900 2300 2050 2600]
new average : 1958.3333333333333


In [87]:
#9
"""
Find: 
1. Shape and ndim.  
2. Total quality score of each machine.  
3. Average quality score of each machine.  
4. Machine with the highest individual score.  
5. Lowest individual score.  
6. Extract Week 3 and Week 4 for all machines.  
7. Extract all weeks of Machine 3.  
8. Add 1 point to every score.  
9. Find the new maximum.  
10. Check whether the new maximum reaches 100. 

Rows = Machines 
Columns = Week 1, Week 2, Week 3, Week 4
"""

quality = [ 
[96, 94, 97, 95], 
[91, 89, 93, 90], 
[98, 97, 99, 96], 
[87, 92, 90, 88] 
] 

arr = np.array(quality)

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"Total quality score of each machine : {arr.sum(axis=1)}")
print(f"Average quality score of each machine : {arr.mean(axis=1)}")
print(f"Machine with the highest individual score : {arr.max(axis=1)}")
print(f"Lowest individual score : {arr.min(axis=1)}")
print(f"Week 3 and Week 4 for all machines : {arr[:,-2:]}")
print(f"all weeks of Machine 3 : {arr[2]}")

new = arr + 1
print(f"new maximum : {new.max()}")

if new.max() >= 100:
    print("Yes, the new maximum reaches 100")
else:
    print("No, the new maximum not reaches 100")


Shape : (4, 4)
Ndim : 2
Total quality score of each machine : [382 363 390 357]
Average quality score of each machine : [95.5  90.75 97.5  89.25]
Machine with the highest individual score : [97 93 99 92]
Lowest individual score : [94 89 96 87]
Week 3 and Week 4 for all machines : [[97 95]
 [93 90]
 [99 96]
 [90 88]]
all weeks of Machine 3 : [98 97 99 96]
new maximum : 100
Yes, the new maximum reaches 100


In [103]:
#10
"""
Perform: 
1. Create the 2D NumPy array.  
2. Print shape, ndim and dtype.  
3. Extract the Monthly Spend column.  
4. Extract the Orders column.  
5. Find average monthly spend.  
6. Find maximum monthly spend.  
7. Find minimum monthly spend.  
8. Extract the first 3 customers.  
9. Extract Age and Monthly Spend for all customers.  
10. Increase Monthly Spend by 10% and display the updated customer data.

Rows = Customers 
Columns = Age, Monthly Spend, Orders
"""

customers = [ 
[21, 4500, 5], 
[28, 7200, 8], 
[35, 6800, 7], 
[42, 9200, 10], 
[31, 5600, 6], 
[25, 8100, 9] 
]

arr = np.array(customers)

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"Dtype : {arr.dtype}")
print(f"Monthly Spend column : {arr[:,1]}")
print(f"Orders column : {arr[:,-1]}")
print(f"average monthly spend : {arr[:,1].mean()}")
print(f"maximum monthly spend : {arr[:,1].max()}")
print(f"minimum monthly spend : {arr[:,1].min()}")
print(f"first 3 customers : {arr[:3]}")
print(f"Age and Monthly Spend for all customers : {arr[:,:2]}")

arr[:,1] = arr[:,1] + (arr[:,1] * 10) / 100
print(f"updated customer data : {arr}")

Shape : (6, 3)
Ndim : 2
Dtype : int64
Monthly Spend column : [4500 7200 6800 9200 5600 8100]
Orders column : [ 5  8  7 10  6  9]
average monthly spend : 6900.0
maximum monthly spend : 9200
minimum monthly spend : 4500
first 3 customers : [[  21 4500    5]
 [  28 7200    8]
 [  35 6800    7]]
Age and Monthly Spend for all customers : [[  21 4500]
 [  28 7200]
 [  35 6800]
 [  42 9200]
 [  31 5600]
 [  25 8100]]
updated customer data : [[   21  4950     5]
 [   28  7920     8]
 [   35  7480     7]
 [   42 10120    10]
 [   31  6160     6]
 [   25  8910     9]]
