In [2]:
import numpy as np

In [3]:
#1
"""
Perform: 
1. Create a NumPy array.  
2. Find the total visitors.  
3. Find the average visitors.  
4. Find the maximum visitors.  
5. Extract visitors from Day 3 to Day 7.  
6. Extract the last 3 days.  
7. Increase every day's visitors by 5%.  
8. Find the new maximum.  
9. Check whether the new maximum exceeds ₹ — ignore currency; treat it as 
visitor count — 1900.  
10. Print the shape and ndim.  
"""

visitors = [1250, 1380, 1425, 1190, 1560, 1680, 1490, 1720, 1810, 1650] 

arr = np.array(visitors)

print(f"total visitors : {arr.sum()}")
print(f"average visitors : {arr.mean()}")
print(f"maximum visitors : {arr.max()}")
print(f"visitors from Day 3 to Day 7 : {arr[2:7]}")
print(f"last 3 days : {arr[-3:]}")

increased = arr + (arr * 5) / 100
print(f"new maximum : {increased.max()}")

if increased.max() > 1900:
    print("Yes, the new maximum exceeds 1900")
else:
    print("No, the new maximum not exceeds 1900")

print(f"Shape : {increased.shape}")
print(f"Ndim : {increased.ndim}")


total visitors : 15155
average visitors : 1515.5
maximum visitors : 1810
visitors from Day 3 to Day 7 : [1425 1190 1560 1680 1490]
last 3 days : [1720 1810 1650]
new maximum : 1900.5
Yes, the new maximum exceeds 1900
Shape : (10,)
Ndim : 1


In [4]:
#2
"""
Using np.arange(): 
1. Create targets from ₹20,000 up to ₹50,000.  
2. Find the average target.  
3. Find the maximum target.  
4. Extract the first 3 targets.  
5. Extract the last 2 targets.  
6. Increase all targets by 10%.  
7. Find the new maximum. 

A company wants to create monthly sales targets starting from ₹20,000 and 
increasing by ₹5,000. 
"""

sales = np.arange(20000,50001,5000)

print(sales)
print(f"average target : {sales.mean()}")
print(f"maximum target : {sales.max()}")
print(f"first 3 targets : {sales[:3]}")
print(f"last 2 targets : {sales[-2:]}")

increased = sales + (sales * 10) / 100
print(f"new maximum : {increased.max()}")

[20000 25000 30000 35000 40000 45000 50000]
average target : 35000.0
maximum target : 50000
first 3 targets : [20000 25000 30000]
last 2 targets : [45000 50000]
new maximum : 55000.0


In [5]:
#3
"""
Using np.linspace(): 
1. Create the benchmark array.  
2. Find its shape.  
3. Find its ndim.  
4. Find the average benchmark.  
5. Find the maximum and minimum.  
6. Extract the first 3 benchmarks.  
7. Add 5 points to every benchmark.  
8. Find the new maximum. 

An HR team wants to generate 6 evenly spaced performance benchmark scores 
between 60 and 90, including both endpoints. 
"""

benchmark = np.linspace(60,90,6)

print(benchmark)
print(f"Shape : {benchmark.shape}")
print(f"Ndim : {benchmark.ndim}")
print(f"average benchmark : {benchmark.mean()}")
print(f"maximum benchmark : {benchmark.max()}")
print(f"minimum benchmark : {benchmark.min()}")
print(f"first 3 benchmarks : {benchmark[:3]}")

add = benchmark + 5

print(f"New maximum : {add.max()}")

[60. 66. 72. 78. 84. 90.]
Shape : (6,)
Ndim : 1
average benchmark : 75.0
maximum benchmark : 90.0
minimum benchmark : 60.0
first 3 benchmarks : [60. 66. 72.]
New maximum : 95.0


In [6]:
#4
"""
Perform: 
1. Create the 2D array.  
2. Extract the Monthly Spend column.  
3. Extract the Orders column.  
4. Extract the first 4 customers.  
5. Extract Age and Orders for all customers.  
6. Find total Monthly Spend.  
7. Find average Orders.  
8. Find the highest individual Monthly Spend.  
9. Add 500 to every Monthly Spend.  
10. Display the updated customer data.  

Columns: 
Age → Monthly Spend → Orders
"""

customers = [ 
    [21, 4500, 5], 
    [28, 7200, 8], 
    [35, 6800, 7], 
    [42, 9200, 10], 
    [31, 5600, 6], 
    [25, 8100, 9] 
]

arr = np.array(customers)

print(f"Monthly Spend : {arr[:,1]}")
print(f"Orders : {arr[:,-1]}")
print(f"first 4 customers : {arr[:4]}")
print(f"Age and Orders for all customers : {arr[:,::2]}")
print(f"total Monthly Spend : {arr[:,1].sum()}")
print(f"average Orders : {arr[:,-1].mean()}")
print(f"highest individual Monthly Spend : {arr[:,1].max()}")

arr[:,1] = arr[:,1] + 500

print(f"updated customer data : {arr}")


Monthly Spend : [4500 7200 6800 9200 5600 8100]
Orders : [ 5  8  7 10  6  9]
first 4 customers : [[  21 4500    5]
 [  28 7200    8]
 [  35 6800    7]
 [  42 9200   10]]
Age and Orders for all customers : [[21  5]
 [28  8]
 [35  7]
 [42 10]
 [31  6]
 [25  9]]
total Monthly Spend : 41400
average Orders : 7.5
highest individual Monthly Spend : 9200
updated customer data : [[  21 5000    5]
 [  28 7700    8]
 [  35 7300    7]
 [  42 9700   10]
 [  31 6100    6]
 [  25 8600    9]]


In [7]:
#5
"""
Perform: 
1. Find shape and ndim.  
2. Find total sales of each store.  
3. Find average sales of each store.  
4. Find total sales of each quarter.  
5. Extract Q2 and Q3 for all stores.  
6. Extract all quarters of Store 3.  
7. Find the highest individual sales value.  
8. Find the lowest individual sales value.  
9. Increase all sales by 8%.  
10. Find the new maximum.   

Rows = Stores 
Columns = Q1, Q2, Q3, Q4 
"""

sales = [ 
    [12000, 15000, 18000, 21000], 
    [14000, 17000, 16000, 23000], 
    [11000, 13000, 19000, 22000], 
    [16000, 18000, 21000, 25000] 
]

arr = np.array(sales)

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"average sales of each store : {arr.mean(axis=1)}")
print(f"total sales of each quarter : {arr.sum(axis=0)}")
print(f"Q2 and Q3 for all stores : {arr[:,1:3]}")
print(f"all quarters of Store 3 : {arr[2]}")
print(f"highest individual sales value : {arr.max(axis=1)}")
print(f"lowest individual sales value : {arr.min(axis=1)}")

increased = arr + (arr * 8) / 100

print(f"new maximum : {increased.max()}")

Shape : (4, 4)
Ndim : 2
average sales of each store : [16500. 17500. 16250. 20000.]
total sales of each quarter : [53000 63000 74000 91000]
Q2 and Q3 for all stores : [[15000 18000]
 [17000 16000]
 [13000 19000]
 [18000 21000]]
all quarters of Store 3 : [11000 13000 19000 22000]
highest individual sales value : [21000 23000 22000 25000]
lowest individual sales value : [12000 14000 11000 16000]
new maximum : 27000.0


In [8]:
#6
"""
Using np.arange(): 
1. Generate all employee IDs.  
2. Find the shape and ndim.  
3. Extract the first 5 IDs.  
4. Extract IDs from 1010 to 1015.  
5. Extract the last 4 IDs.  
6. Add 100 to every ID.  
7. Find the maximum updated ID.  

A company has employee IDs starting from 1001 and ending at 1020. 
"""

id = np.arange(1001, 1021)

print(f"Shape : {id.shape}")
print(f"Ndim : {id.ndim}")
print(f"first 5 IDs : {id[:5]}")
print(f"IDs from 1010 to 1015 : {id[9:15]}")
print(f"last 4 IDs : {id[-4:]}")

add = id + 100

print(f"maximum updated ID : {add.max()}")

Shape : (20,)
Ndim : 1
first 5 IDs : [1001 1002 1003 1004 1005]
IDs from 1010 to 1015 : [1010 1011 1012 1013 1014 1015]
last 4 IDs : [1017 1018 1019 1020]
maximum updated ID : 1120


In [9]:
#7
"""
Using a NumPy random function you have learned: 
1. Generate 10 random values.  
2. Find the average accuracy.  
3. Find the maximum accuracy.  
4. Find the minimum accuracy.  
5. Extract the first 5 values.  
6. Add 0.05 to every accuracy value.  
7. Find the new maximum. 

You need to simulate 10 model accuracy scores between 0 and 1 using NumPy 
random numbers. 
"""

num = np.random.random(10)

print(f"average accuracy : {num.mean()}")
print(f"maximum accuracy : {num.max()}")
print(f"minimum accuracy : {num.min()}")
print(f"first 5 values : {num[:5]}")

add = num + 0.05

print(f"naw maximum : {add.max()}")

average accuracy : 0.5768293424515579
maximum accuracy : 0.9690286997142664
minimum accuracy : 0.19081581406164727
first 5 values : [0.83296421 0.33924503 0.47792568 0.53102096 0.66837043]
naw maximum : 1.0190286997142664


In [21]:
#8
"""
Perform: 
1. Create it using np.identity().  
2. Create another 4 × 4 identity matrix using np.eye().  
3. Check their shapes.  
4. Check their ndims.  
5. Find the maximum value of each matrix.  
6. Find the minimum value of each matrix.  
7. Explain from your output whether both matrices contain the same values. 

A Data Science team wants to create an identity matrix of size 4 × 4. 
"""

identity = np.identity(4)
eye = np.eye(4)

print(f"identity : {identity}")
print(f"eye : {eye}")

print(f"Shape of identity : {identity.shape}")
print(f"Shape of eye : {eye.shape}")

print(f"Ndim of identity : {identity.ndim}")
print(f"Ndim of eye : {eye.ndim}")

print(f"maximum value of identity : {identity.max()}")
print(f"maximum value of eye : {eye.max()}")

print(f"minimum value of identity : {identity.min()}")
print(f"minimum value of eye : {eye.min()}")

print("Both matrices contain the same values: Yes")

identity : [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
eye : [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape of identity : (4, 4)
Shape of eye : (4, 4)
Ndim of identity : 2
Ndim of eye : 2
maximum value of identity : 1.0
maximum value of eye : 1.0
minimum value of identity : 0.0
minimum value of eye : 0.0
Both matrices contain the same values: Yes


In [31]:
#9
"""
Perform: 
1. Create the 2D array.  
2. Find shape and ndim.  
3. Extract all Monthly Spend values.  
4. Extract all Orders values.  
5. Find average Monthly Spend.  
6. Find maximum Monthly Spend.  
7. Find minimum Monthly Spend.  
8. Extract customers 3 to 6.  
9. Add ₹500 to Monthly Spend.  
10. Find the new average Monthly Spend.  

Columns: 
Age → Monthly Spend → Orders 
"""

data = [ 
    [22, 3500, 3], 
    [29, 6200, 6], 
    [41, 8500, 9], 
    [35, 7200, 7], 
    [26, 4800, 4], 
    [39, 9100, 10], 
    [31, 6800, 8], 
    [24, 4200, 3] 
]

arr = np.array(data)

print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"all Monthly Spend values : {arr[:,1]}")
print(f"all Orders values : {arr[:,-1]}")
print(f"average Monthly Spend : {arr[:,1].mean()}")
print(f"maximum Monthly Spend : {arr[:,1].max()}")
print(f"minimum Monthly Spend : {arr[:,1].min()}")
print(f"customers 3 to 6 : {arr[2:6]}")

add = arr.copy()
add[:,1] = add[:,1] + 500

print(f"new average Monthly Spend : {add[:,1].mean()}")

Shape : (8, 3)
Ndim : 2
all Monthly Spend values : [3500 6200 8500 7200 4800 9100 6800 4200]
all Orders values : [ 3  6  9  7  4 10  8  3]
average Monthly Spend : 6287.5
maximum Monthly Spend : 9100
minimum Monthly Spend : 3500
customers 3 to 6 : [[  41 8500    9]
 [  35 7200    7]
 [  26 4800    4]
 [  39 9100   10]]
new average Monthly Spend : 6787.5


In [45]:
#10
"""

"""

linespace = np.linspace(10,50,5)
arange = np.arange(100,600,100)
eye = np.eye(5)
random = np.random.random(5)

print(f"Linespace")
print(f"average : {linespace.mean()}")
print(f"maximum : {linespace.max()}")
print(f"minimum : {linespace.min()}")
print()

print(f"Arange")
print(f"total : {arange.sum()}")
print(f"average : {arange.mean()}")
print(f"maximum : {arange.max()}")
print()

print(f"Random")
print(f"average : {random.mean()}")
print(f"maximum : {random.max()}")
print(f"minimum : {random.min()}")
print()

increased = linespace + (linespace * 10) / 100

print(f"Increased linespace : {increased}")


Linespace
average : 30.0
maximum : 50.0
minimum : 10.0

Arange
total : 1500
average : 300.0
maximum : 500

Random
average : 0.5338252459948707
maximum : 0.9440951044937675
minimum : 0.0861203947512379

Increased linespace : [11. 22. 33. 44. 55.]
