In [1]:
import numpy as np

In [2]:
#1
"""
A company has monthly sales targets from ₹25,000 to ₹75,000, increasing by ₹5,000. 
 
Using NumPy: 
1. Create the target array using np.arange().  
2. Find the total target.  
3. Find the average target.  
4. Find the highest target.  
5. Extract the first 4 targets.  
6. Extract the last 3 targets.  
7. Increase all targets by 12%.  
8. Find the new average target.  
9. Find the new maximum target.  
10. Display shape and ndim. 
"""

sales = np.arange(25000,75001,5000)

print(f"Total target : {sales.sum()}")
print(f"Average target : {sales.mean()}")
print(f"Highest target : {sales.max()}")
print(f"first 4 targets : {sales[:4]}")
print(f"last 3 targets : {sales[-3:]}")

increased = sales + (sales * 12) / 100

print(f"new average target : {increased.mean()}")
print(f"new maximum target : {increased.max()}")
print(f"Shape : {increased.shape}")
print(f"Ndim : {increased.ndim}")

Total target : 550000
Average target : 50000.0
Highest target : 75000
first 4 targets : [25000 30000 35000 40000]
last 3 targets : [65000 70000 75000]
new average target : 56000.0
new maximum target : 84000.0
Shape : (11,)
Ndim : 1


In [3]:
#2
"""
HR wants 8 evenly spaced performance scores from 55 to 90, including both 
endpoints. 
 
Using np.linspace(): 
1. Create the array.  
2. Find the average score.  
3. Find the maximum and minimum.  
4. Extract the first 3 scores.  
5. Extract the last 2 scores.  
6. Add 5 points to every score.  
7. Find the new maximum.  
8. Display shape and ndim. 
"""

scores = np.linspace(55,90,8)

print(f"Array : {scores}")
print(f"average score : {scores.mean()}")
print(f"maximum score : {scores.max()}")
print(f"minimum score : {scores.min()}")
print(f"first 3 scores : {scores[:3]}")
print(f"last 2 scores : {scores[-2:]}")

add = scores + 5

print(f"new maximum : {add.max()}")
print(f"shape : {add.shape}")
print(f"ndim : {add.ndim}")

Array : [55. 60. 65. 70. 75. 80. 85. 90.]
average score : 72.5
maximum score : 90.0
minimum score : 55.0
first 3 scores : [55. 60. 65.]
last 2 scores : [85. 90.]
new maximum : 95.0
shape : (8,)
ndim : 1


In [4]:
#3
"""
Create a NumPy array and: 
1. Display its shape and ndim.  
2. Find total sales for each store.  
3. Find average sales for each store.  
4. Find total sales for each quarter.  
5. Extract Q2 and Q3 for all stores.  
6. Extract all quarters for Store 4.  
7. Find the highest individual sales value.  
8. Find the lowest individual sales value.  
9. Increase only Q4 sales by 10%.  
10. Find the new highest individual sales value. 
"""

sales = [ 
    [12000, 15000, 18000, 21000], 
    [14000, 16000, 19000, 23000], 
    [11000, 17000, 20000, 22000], 
    [15000, 18000, 21000, 25000], 
    [13000, 15500, 17500, 24000] 
]

arr = np.array(sales)

print(f"Array : {arr}")
print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"total sales for each store : {arr.sum(axis=1)}")
print(f"average sales for each store : {arr.mean(axis=1)}")
print(f"total sales for each quarter : {arr.sum(axis=0)}")
print(f"Q2 and Q3 for all stores : {arr[:,1:3]}")
print(f"all quarters for Store 4 : {arr[3]}")
print(f"highest individual sales value : {arr.max(axis=1)}")
print(f"lowest individual sales value : {arr.min(axis=1)}")

arr[:,-1] = arr[:,-1] + (arr[:,-1] * 10) / 100

print(f"new highest individual sales value : {arr.max(axis=1)}")

Array : [[12000 15000 18000 21000]
 [14000 16000 19000 23000]
 [11000 17000 20000 22000]
 [15000 18000 21000 25000]
 [13000 15500 17500 24000]]
Shape : (5, 4)
Ndim : 2
total sales for each store : [66000 72000 70000 79000 70000]
average sales for each store : [16500. 18000. 17500. 19750. 17500.]
total sales for each quarter : [ 65000  81500  95500 115000]
Q2 and Q3 for all stores : [[15000 18000]
 [16000 19000]
 [17000 20000]
 [18000 21000]
 [15500 17500]]
all quarters for Store 4 : [15000 18000 21000 25000]
highest individual sales value : [21000 23000 22000 25000 24000]
lowest individual sales value : [12000 14000 11000 15000 13000]
new highest individual sales value : [23100 25300 24200 27500 26400]


In [5]:
#4
"""
Tasks: 
1. Create the 2D array.  
2. Display shape and ndim.  
3. Extract all ages.  
4. Extract all monthly spending values.  
5. Extract all order values.  
6. Find average monthly spend.  
7. Find maximum individual monthly spend.  
8. Extract customers 2 to 5.  
9. Increase only monthly spending by ₹750.  
10. Find the new average monthly spend. 

Columns: 
Age | Monthly Spend | Orders 
"""

customers = [ 
    [21, 4200, 4], 
    [27, 6500, 6], 
    [32, 7800, 8], 
    [39, 9200, 10], 
    [25, 5100, 5], 
    [44, 8600, 9], 
    [30, 7300, 7] 
]

arr = np.array(customers)

print(f"Array : {arr}")
print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"ages : {arr[:,0]}")
print(f"monthly spending values : {arr[:,1]}")
print(f"order values : {arr[:,2]}")
print(f"average monthly spend : {arr[:,1].mean()}")
print(f"maximum individual monthly spend : {arr[:,1].max()}")
print(f"customers 2 to 5 : {arr[1:5]}")

increased = arr.copy()
increased[:,1] = increased[:,1] + 750

print(f"new average monthly spend : {increased[:,1].mean()}")

Array : [[  21 4200    4]
 [  27 6500    6]
 [  32 7800    8]
 [  39 9200   10]
 [  25 5100    5]
 [  44 8600    9]
 [  30 7300    7]]
Shape : (7, 3)
Ndim : 2
ages : [21 27 32 39 25 44 30]
monthly spending values : [4200 6500 7800 9200 5100 8600 7300]
order values : [ 4  6  8 10  5  9  7]
average monthly spend : 6957.142857142857
maximum individual monthly spend : 9200
customers 2 to 5 : [[  27 6500    6]
 [  32 7800    8]
 [  39 9200   10]
 [  25 5100    5]]
new average monthly spend : 7707.142857142857


In [6]:
#5
"""
A company has employee IDs starting from 2001 to 2040. 
 
Using np.arange(): 
1. Generate all IDs.  
2. Display shape and ndim.  
3. Extract the first 6 IDs.  
4. Extract IDs from 2015 to 2022.  
5. Extract the last 5 IDs.  
6. Add 500 to every ID.  
7. Find the maximum updated ID.  
8. Find the minimum updated ID.  
9. Extract every 3rd ID from the original array.  
10. Display the final array.  
"""

ids = np.arange(2001,2041)

print(f"All ids : {ids}")
print(f"Shape : {ids.shape}")
print(f"Ndim : {ids.ndim}")
print(f"first 6 IDs : {ids[:6]}")
print(f"from 2015 to 2022 : {ids[14:22]}")
print(f"last 5 IDs : {ids[-5:]}")

add = ids + 500

print(f"maximum updated ID : {add.max()}")
print(f"minimum updated ID : {add.min()}")
print(f"every 3rd ID from the original array : {ids[2::3]}")
print(f"final array : {add}")

All ids : [2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028
 2029 2030 2031 2032 2033 2034 2035 2036 2037 2038 2039 2040]
Shape : (40,)
Ndim : 1
first 6 IDs : [2001 2002 2003 2004 2005 2006]
from 2015 to 2022 : [2015 2016 2017 2018 2019 2020 2021 2022]
last 5 IDs : [2036 2037 2038 2039 2040]
maximum updated ID : 2540
minimum updated ID : 2501
every 3rd ID from the original array : [2003 2006 2009 2012 2015 2018 2021 2024 2027 2030 2033 2036 2039]
final array : [2501 2502 2503 2504 2505 2506 2507 2508 2509 2510 2511 2512 2513 2514
 2515 2516 2517 2518 2519 2520 2521 2522 2523 2524 2525 2526 2527 2528
 2529 2530 2531 2532 2533 2534 2535 2536 2537 2538 2539 2540]


In [7]:
#6
"""
Generate 15 random values using a NumPy random function you have learned. 
Treat them as model accuracy values. 
 
Tasks: 
1. Generate 15 random values.  
2. Find the average accuracy.  
3. Find the maximum accuracy.  
4. Find the minimum accuracy.  
5. Extract the first 5 values.  
6. Add 0.10 to every value.  
7. Find the new maximum.  
8. Find the new average.  
9. Check whether the new maximum is greater than 1.  
10. Display shape and ndim.  
"""

num = np.random.random(15)

print(f"Values : {num}")
print(f"average accuracy : {num.mean()}")
print(f"maximum accuracy : {num.max()}")
print(f"minimum accuracy : {num.min()}")
print(f"first 5 values : {num[:5]}")

new = num + 0.10

print(f"the new maximum : {new.max()}")
print(f"the new average : {new.mean()}")

if new.max() > 1:
    print("Yes, the new maximum is greater than 1")
else:
    print("No, the new maximum is not greater than 1")

print(f"Shape : {new.shape}")
print(f"Ndim : {new.ndim}")


Values : [0.50447688 0.8087465  0.20535069 0.7628031  0.16714087 0.02944429
 0.20020655 0.56294208 0.02765799 0.04150749 0.51729842 0.15704742
 0.68352703 0.35428443 0.30309795]
average accuracy : 0.35503544464562636
maximum accuracy : 0.8087464988323511
minimum accuracy : 0.027657987459518085
first 5 values : [0.50447688 0.8087465  0.20535069 0.7628031  0.16714087]
the new maximum : 0.908746498832351
the new average : 0.45503544464562634
No, the new maximum is not greater than 1
Shape : (15,)
Ndim : 1


In [8]:
#7
"""
Create these two matrices: 
A = np.eye(5) 
B = np.identity(5) 
 
Tasks: 
1. Display both matrices.  
2. Display their shapes.  
3. Display their dimensions.  
4. Find the maximum value of each.  
5. Find the minimum value of each.  
6. Calculate the total of each matrix.  
7. Compare whether both matrices have the same values.  
8. Extract the third row from both matrices.  
9. Extract the third column from both matrices.  
10. Explain in one sentence why np.eye(5) and np.identity(5) produce the same 
5×5 result here. 
"""

A = np.eye(5)
B = np.identity(5)

print(f"A : {A}")
print(f"B : {B}")

print(f"Shape of A : {A.shape}")
print(f"Shape of B : {B.shape}")

print(f"Dimensions of A : {A.ndim}")
print(f"Dimensions of B : {B.ndim}")

print(f"maximum value of A : {A.max()}")
print(f"maximum value of B : {B.max()}")

print(f"minimum value of A : {A.min()}")
print(f"minimum value of B : {B.min()}")

print(f"total of A : {A.sum()}")
print(f"total of B : {B.sum()}")

if np.array_equal(A,B):
    print("Yes, both matrices have the same values")
else:
    print("No, both matrices haven't the same values")

print(f"third row from A : {A[2]}")
print(f"third row from B : {B[2]}")

print(f"third column from A : {A[:,2]}")
print(f"third column from B : {B[:,2]}")

print("Both produce the same 5x5 result because we put a same input in both but using eye we can create flexible matrix but can't with identity it can produce in square matrix")


A : [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
B : [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Shape of A : (5, 5)
Shape of B : (5, 5)
Dimensions of A : 2
Dimensions of B : 2
maximum value of A : 1.0
maximum value of B : 1.0
minimum value of A : 0.0
minimum value of B : 0.0
total of A : 5.0
total of B : 5.0
Yes, both matrices have the same values
third row from A : [0. 0. 1. 0. 0.]
third row from B : [0. 0. 1. 0. 0.]
third column from A : [0. 0. 1. 0. 0.]
third column from B : [0. 0. 1. 0. 0.]
Both produce the same 5x5 result because we put a same input in both but using eye we can create flexible matrix but can't with identity it can produce in square matrix


In [9]:
#8
"""
Tasks: 
1. Create the array.  
2. Find total sales for each store.  
3. Find average sales for each store.  
4. Find total sales for each quarter.  
5. Find the highest individual sales value.  
6. Find the lowest individual sales value.  
7. Extract Q1 and Q4 for all stores.  
8. Extract Q2 and Q3 for Store 3.  
9. Increase all sales by 15%.  
10. Find the new highest individual sales value. 

Rows = Stores 
Columns = Q1, Q2, Q3, Q4 
"""

sales = [ 
    [15000, 18000, 21000, 24000], 
    [12000, 16000, 19000, 22000], 
    [17000, 20000, 23000, 26000], 
    [11000, 14000, 18000, 21000] 
]

arr = np.array(sales)

print(f"Array : {arr}")
print(f"total sales for each store : {arr.sum(axis=1)}")
print(f"average sales for each store : {arr.mean(axis=1)}")
print(f"total sales for each quarter : {arr.sum(axis=0)}")
print(f"highest individual sales value : {arr.max(axis=1)}")
print(f"lowest individual sales value : {arr.min(axis=1)}")
print(f"Q1 and Q4 for all stores : {arr[:,(0,3)]}")
print(f"Q2 and Q3 for Store 3 : {arr[2,(1,2)]}")

increased = arr + (arr * 15) / 100

print(f"new highest individual sales value : {increased.max(axis=1)}")

Array : [[15000 18000 21000 24000]
 [12000 16000 19000 22000]
 [17000 20000 23000 26000]
 [11000 14000 18000 21000]]
total sales for each store : [78000 69000 86000 64000]
average sales for each store : [19500. 17250. 21500. 16000.]
total sales for each quarter : [55000 68000 81000 93000]
highest individual sales value : [24000 22000 26000 21000]
lowest individual sales value : [15000 12000 17000 11000]
Q1 and Q4 for all stores : [[15000 24000]
 [12000 22000]
 [17000 26000]
 [11000 21000]]
Q2 and Q3 for Store 3 : [20000 23000]
new highest individual sales value : [27600. 25300. 29900. 24150.]


In [10]:
#9
"""
Create: 
targets = np.arange(10000, 60001, 10000) 
benchmarks = np.linspace(60, 100, 6) 
matrix = np.eye(4) 
random_values = np.random.random(8) 
 
Perform: 
1. Display all four arrays/matrices.  
2. Find the average of targets.  
3. Find the maximum of targets.  
4. Find the average of benchmarks.  
5. Find the minimum of benchmarks.  
6. Find the total of matrix.  
7. Find the maximum of random_values.  
8. Add 10% to targets.  
9. Add 5 points to benchmarks.  
10. Display the shape and ndim of all four. 
"""

targets = np.arange(10000, 60001, 10000) 
benchmarks = np.linspace(60, 100, 6) 
matrix = np.eye(4) 
random_values = np.random.random(8) 

print(f"Target : {targets}")
print(f"Benchmark : {benchmarks}")
print(f"Matrix : {matrix}")
print(f"Random_values : {random_values}")

print(f"average of targets : {targets.mean()}")
print(f"maximum of targets : {targets.max()}")
print(f"average of benchmarks : {benchmarks.mean()}")
print(f"minimum of benchmarks : {benchmarks.min()}")

print(f"total of matrix : {matrix.sum()}")
print(f"maximum of random_values : {random_values.max()}")

add_target = targets + (targets * 10) / 100
add_benchmarks = benchmarks + 5

print(f"Shape of target : {targets.shape}")
print(f"Ndim of target : {targets.ndim}")

print(f"Shape of benchmarks : {benchmarks.shape}")
print(f"Ndim of benchmarks : {benchmarks.ndim}")

print(f"Shape of matrix : {matrix.shape}")
print(f"Ndim of matrix : {matrix.ndim}")

print(f"Shape of random_values : {random_values.shape}")
print(f"Ndim of random_values : {random_values.ndim}")

Target : [10000 20000 30000 40000 50000 60000]
Benchmark : [ 60.  68.  76.  84.  92. 100.]
Matrix : [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random_values : [0.18012598 0.1910765  0.80877815 0.12788842 0.59160234 0.65131144
 0.63170293 0.67253983]
average of targets : 35000.0
maximum of targets : 60000
average of benchmarks : 80.0
minimum of benchmarks : 60.0
total of matrix : 4.0
maximum of random_values : 0.8087781477082499
Shape of target : (6,)
Ndim of target : 1
Shape of benchmarks : (6,)
Ndim of benchmarks : 1
Shape of matrix : (4, 4)
Ndim of matrix : 2
Shape of random_values : (8,)
Ndim of random_values : 1


In [28]:
#10
"""
Tasks: 
1. Create the NumPy array.  
2. Display shape and ndim.  
3. Extract all employee IDs.  
4. Extract all performance scores.  
5. Extract all salaries.  
6. Find the average performance score.  
7. Find the highest individual salary.  
8. Extract employees 103 to 106.  
9. Increase all salaries by 8%.  
10. Find the new highest individual salary.

Columns: 
Employee ID | Performance Score | Salary
"""

data = [ 
    [101, 72, 45000], 
    [102, 85, 52000], 
    [103, 68, 39000], 
    [104, 91, 61000], 
    [105, 77, 48000], 
    [106, 88, 57000] 
]

arr = np.array(data)

print(f"Array : {arr}")
print(f"Shape : {arr.shape}")
print(f"Ndim : {arr.ndim}")
print(f"all employee IDs : {arr[:,0]}")
print(f"all performance scores : {arr[:,1]}")
print(f"all salaries : {arr[:,2]}")
print(f"average performance score : {arr[:,1].mean()}")
print(f"highest individual salary : {arr[:,2].max()}")
print(f"employees 103 to 106 : {arr[2:]}")

increased = arr.copy()
increased[:,2] = increased[:,2] + (increased[:,2] * 8) / 100

print(f"new highest individual salary : {increased.max()}")

Array : [[  101    72 45000]
 [  102    85 52000]
 [  103    68 39000]
 [  104    91 61000]
 [  105    77 48000]
 [  106    88 57000]]
Shape : (6, 3)
Ndim : 2
all employee IDs : [101 102 103 104 105 106]
all performance scores : [72 85 68 91 77 88]
all salaries : [45000 52000 39000 61000 48000 57000]
average performance score : 80.16666666666667
highest individual salary : 61000
employees 103 to 106 : [[  103    68 39000]
 [  104    91 61000]
 [  105    77 48000]
 [  106    88 57000]]
new highest individual salary : 65880
