In [1]:
import numpy as np

In [2]:
#1
"""
Generate revenue targets from ₹25,000 to ₹75,000, increasing by ₹5,000. 
 
Tasks: 
1. Create the array using arange().  
2. Display the array.  
3. Find total revenue target.  
4. Find average target.  
5. Find highest target.  
6. Extract the first 4 targets.  
7. Extract the last 3 targets.  
8. Increase all targets by 12%.  
9. Find the new highest target.  
10. Display shape and ndim. 
"""

targets = np.arange(25000,75001,5000)

print(f"Array : {targets}")
print(f"total revenue target : {targets.sum()}")
print(f"average target : {targets.mean()}")
print(f"highest target : {targets.max()}")
print(f"first 4 targets : {targets[:4]}")
print(f"last 3 targets : {targets[-3:]}")

increased = targets + (targets * 12) / 100

print(f"new highest target : {increased.max()}")
print(f"shape : {increased.shape}")
print(f"ndim : {increased.ndim}")

Array : [25000 30000 35000 40000 45000 50000 55000 60000 65000 70000 75000]
total revenue target : 550000
average target : 50000.0
highest target : 75000
first 4 targets : [25000 30000 35000 40000]
last 3 targets : [65000 70000 75000]
new highest target : 84000.0
shape : (11,)
ndim : 1


In [3]:
#2
"""
Generate 8 evenly spaced scores from 55 to 90 using linspace(). 
 
Tasks: 
1. Create the array.  
2. Display the array.  
3. Find average score.  
4. Find highest score.  
5. Find lowest score.  
6. Extract the first 3 scores.  
7. Extract the last 2 scores.  
8. Add 5 points to every score.  
9. Find the new highest score.  
10. Display shape and ndim. 
"""

scores = np.linspace(55,90,8)

print(f"Array : {scores}")
print(f"average score : {scores.mean()}")
print(f"highest score : {scores.max()}")
print(f"lowest score : {scores.min()}")
print(f"first 3 scores : {scores[:3]}")
print(f"last 2 scores : {scores[-2:]}")

add = scores + 5

print(f"new highest score : {add.max()}")
print(f"shape : {add.shape}")
print(f"ndim : {add.ndim}")

Array : [55. 60. 65. 70. 75. 80. 85. 90.]
average score : 72.5
highest score : 90.0
lowest score : 55.0
first 3 scores : [55. 60. 65.]
last 2 scores : [85. 90.]
new highest score : 95.0
shape : (8,)
ndim : 1


In [4]:
#3
"""
Columns: Q1 | Q2 | Q3 | Q4 
 
Tasks: 
1. Create the 2D array.  
2. Display shape and ndim.  
3. Find total sales for each store.  
4. Find average sales for each store.  
5. Find total sales for each quarter.  
6. Extract Q2 and Q3 for all stores.  
7. Extract all quarters for Store 4.  
8. Find the highest individual sales value.  
9. Increase only Q4 sales by 10%.  
10. Find the new highest individual sales value. 
"""

sales = [ 
    [12000, 15000, 18000, 21000], 
    [14000, 16000, 19000, 23000], 
    [11000, 17000, 20000, 22000], 
    [15000, 18000, 21000, 25000], 
    [13000, 15500, 17500, 24000] 
]

arr = np.array(sales)

print(f"Array : {arr}")
print(f"shape : {arr.shape}")
print(f"ndim : {arr.ndim}")
print(f"total sales for each store : {arr.sum(axis=1)}")
print(f"average sales for each store : {arr.mean(axis=1)}")
print(f"total sales for each quarter : {arr.sum(axis=0)}")
print(f"Q2 and Q3 for all stores : {arr[:,(1,2)]}")
print(f"all quarters for Store 4 : {arr[3]}")
print(f"highest individual sales value : {arr.max()}")

increased = arr.copy()

increased[:,-1] = increased[:,-1] + (increased[:,-1] * 10) / 100

print(f"new highest individual sales value : {increased.max()}")

Array : [[12000 15000 18000 21000]
 [14000 16000 19000 23000]
 [11000 17000 20000 22000]
 [15000 18000 21000 25000]
 [13000 15500 17500 24000]]
shape : (5, 4)
ndim : 2
total sales for each store : [66000 72000 70000 79000 70000]
average sales for each store : [16500. 18000. 17500. 19750. 17500.]
total sales for each quarter : [ 65000  81500  95500 115000]
Q2 and Q3 for all stores : [[15000 18000]
 [16000 19000]
 [17000 20000]
 [18000 21000]
 [15500 17500]]
all quarters for Store 4 : [15000 18000 21000 25000]
highest individual sales value : 25000
new highest individual sales value : 27500


In [5]:
#4
"""
Create: 
arr = np.arange(1, 13) 
 
Tasks: 
1. Display the original array.  
2. Display its shape.  
3. Reshape it into a 3 × 4 matrix.  
4. Display the reshaped matrix.  
5. Display the new shape.  
6. Extract the second row.  
7. Extract the third column.  
8. Reshape the original array into a 4 × 3 matrix.  
9. Display its shape.  
10. Display the final matrix. 
"""

arr = np.arange(1, 13) 

print(f"Array : {arr}")
print(f"shape : {arr.shape}")

new = arr.reshape(3,4)

print(f"reshaped matrix : {new}")
print(f"new shape : {new.shape}")

print(f"second row : {new[1]}")
print(f"third column : {new[:,2]}")

neww = arr.reshape(4,3)

print(f"New array shape : {neww.shape}")
print(f"final matrix : {neww}")

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape : (12,)
reshaped matrix : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
new shape : (3, 4)
second row : [5 6 7 8]
third column : [ 3  7 11]
New array shape : (4, 3)
final matrix : [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
#5
"""
Create: 
sales = np.array([ 
    [12000, 15000, 18000], 
    [14000, 17000, 21000], 
    [11000, 16000, 20000] 
]) 
 
Tasks: 
1. Display the original matrix.  
2. Display its shape.  
3. Flatten the matrix.  
4. Display the flattened array.  
5. Display the shape of the flattened array.  
6. Find the total of the flattened array.  
7. Find the highest individual value.  
8. Find the lowest individual value.  
9. Add 1000 to every value in the flattened array.  
10. Find the new highest value. 
"""

sales = np.array([ 
    [12000, 15000, 18000], 
    [14000, 17000, 21000], 
    [11000, 16000, 20000] 
]) 

print(f"original matrix : {sales}")
print(f"shape : {sales.shape}")

flat = sales.flatten()

print(f"flattened array : {flat}")
print(f"shape : {flat.shape}")
print(f"sum : {flat.sum()}")
print(f"highest individual value : {flat.max()}")
print(f"lowest individual value : {flat.min()}")

add = flat + 1000

print(f"new highest value : {add.max()}")

original matrix : [[12000 15000 18000]
 [14000 17000 21000]
 [11000 16000 20000]]
shape : (3, 3)
flattened array : [12000 15000 18000 14000 17000 21000 11000 16000 20000]
shape : (9,)
sum : 144000
highest individual value : 21000
lowest individual value : 11000
new highest value : 22000


In [7]:
#6
"""
Create: 
data = np.array([ 
    [10, 20, 30, 40], 
    [50, 60, 70, 80], 
    [90, 100, 110, 120] 
]) 
 
Tasks: 
1. Display the original array.  
2. Display its shape.  
3. Transpose the array.  
4. Display the transposed array.  
5. Display the transposed shape.  
6. Extract the first row from the transposed array.  
7. Extract the second column from the transposed array.  
8. Find the total of each row of the transposed array.  
9. Find the total of each column of the transposed array.  
10. Find the highest individual value in the transposed array. 
"""

data = np.array([ 
    [10, 20, 30, 40], 
    [50, 60, 70, 80], 
    [90, 100, 110, 120] 
]) 

print(f"original array : {data}")
print(f"shape : {data.shape}")

trans = data.transpose()

print(f"transposed array : {trans}")
print(f"transposed shape : {trans.shape}")
print(f"first row from the transposed array : {trans[0]}")
print(f"second column from the transposed array : {trans[:,1]}")
print(f"total of each row of the transposed array : {trans.sum(axis=1)}")
print(f"total of each column of the transposed array : {trans.sum(axis=0)}")
print(f"highest individual value in the transposed array : {trans.max()}")

original array : [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
shape : (3, 4)
transposed array : [[ 10  50  90]
 [ 20  60 100]
 [ 30  70 110]
 [ 40  80 120]]
transposed shape : (4, 3)
first row from the transposed array : [10 50 90]
second column from the transposed array : [50 60 70 80]
total of each row of the transposed array : [150 180 210 240]
total of each column of the transposed array : [100 260 420]
highest individual value in the transposed array : 120


In [8]:
#7
"""
Create: 
A = np.eye(5) 
B = np.identity(5) 
 
Tasks: 
1. Display both arrays.  
2. Display their shapes.  
3. Display their dimensions.  
4. Find maximum value of both.  
5. Find minimum value of both.  
6. Find total of both.  
7. Check whether both arrays are exactly equal.  
8. Extract the third row from both.  
9. Extract the third column from both.  
10. Transpose A and check its shape.  
"""

A = np.eye(5) 
B = np.identity(5) 

print(f"array A : {A}")
print(f"array B : {B}")

print(f"shape of A : {A.shape}")
print(f"shape of B : {B.shape}")

print(f"dimensions of A : {A.ndim}")
print(f"dimensions of B : {B.ndim}")

print(f"maximum value of A : {A.max()}")
print(f"maximum value of B : {B.max()}")

print(f"minimum value of A : {A.min()}")
print(f"minimum value of B : {B.min()}")

print(f"total of A : {A.sum()}")
print(f"total of B : {B.sum()}")

if np.array_equal(A,B):
    print("Yes, both arrays are exactly equal")
else:
    print("No, both arrays are not exactly equal")

print(f"third row from A : {A[2]}")
print(f"third row from B : {B[2]}")

print(f"third column from A : {A[:,2]}")
print(f"third column from B : {B[:,2]}")

trans_a = A.transpose()

print(f"shape : {trans_a.shape}")


array A : [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
array B : [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
shape of A : (5, 5)
shape of B : (5, 5)
dimensions of A : 2
dimensions of B : 2
maximum value of A : 1.0
maximum value of B : 1.0
minimum value of A : 0.0
minimum value of B : 0.0
total of A : 5.0
total of B : 5.0
Yes, both arrays are exactly equal
third row from A : [0. 0. 1. 0. 0.]
third row from B : [0. 0. 1. 0. 0.]
third column from A : [0. 0. 1. 0. 0.]
third column from B : [0. 0. 1. 0. 0.]
shape : (5, 5)


In [17]:
#8
"""
Generate: 
scores = np.random.random(15) 
 
Tasks: 
1. Generate 15 random values.  
2. Display the array.  
3. Find average score.  
4. Find highest individual score.  
5. Find lowest individual score.  
6. Extract the first 5 scores.  
7. Add 0.10 to every score.  
8. Find the new average.  
9. Find the new highest score.  
10. Use .any() to check whether any new score is greater than 1. 
"""

scores = np.random.random(15) 

print(f"Array = {scores}")
print(f"average score = {scores.mean()}")
print(f"highest score = {scores.max()}")
print(f"lowest score = {scores.min()}")
print(f"first 5 scores = {scores[:5]}")

add = scores + 0.10

print(f"new average : {add.mean()}")
print(f"new highest : {add.max()}")

if (add > 1).any():
    print("Yes atleast one score is greater than 1")
else:
    print("No score is greater than 1")

Array = [0.14618093 0.99995244 0.19816028 0.49405411 0.72858005 0.93750335
 0.34371387 0.19050701 0.01260368 0.88879087 0.17167867 0.6754691
 0.04633417 0.67265165 0.42547511]
average score = 0.4621103528526326
highest score = 0.999952440756093
lowest score = 0.012603683390199572
first 5 scores = [0.14618093 0.99995244 0.19816028 0.49405411 0.72858005]
new average : 0.5621103528526326
new highest : 1.099952440756093
Yes atleast one score is greater than 1


In [26]:
#9
"""
Columns: Employee ID | Performance | Salary 
 
Tasks: 
1. Create the array.  
2. Display shape and ndim.  
3. Extract Employee IDs.  
4. Extract Performance scores.  
5. Extract Salaries.  
6. Find average performance.  
7. Find highest individual salary.  
8. Extract employees 103 to 106.  
9. Increase only salaries by 8%.  
10. Find the new highest individual salary. 
"""

data = [ 
    [101, 72, 45000], 
    [102, 85, 52000], 
    [103, 68, 39000], 
    [104, 91, 61000], 
    [105, 77, 48000], 
    [106, 88, 57000] 
] 

arr = np.array(data)

print(f"shape : {arr.shape}")
print(f"ndim : {arr.ndim}")
print(f"Employee IDs : {arr[:,0]}")
print(f"Performance scores : {arr[:,1]}")
print(f"Salaries : {arr[:,2]}")
print(f"average performance : {arr[:,1].mean()}")
print(f"highest individual salary : {arr[:,2].max()}")
print(f"employees 103 to 106 : {arr[2:]}")

increased = arr.copy()
increased[:,2] = increased[:,2] + (increased[:,2] * 8) / 100

print(f"new highest individual salary : {increased.max()}")


shape : (6, 3)
ndim : 2
Employee IDs : [101 102 103 104 105 106]
Performance scores : [72 85 68 91 77 88]
Salaries : [45000 52000 39000 61000 48000 57000]
average performance : 80.16666666666667
highest individual salary : 61000
employees 103 to 106 : [[  103    68 39000]
 [  104    91 61000]
 [  105    77 48000]
 [  106    88 57000]]
new highest individual salary : 65880


In [44]:
#10
"""
Columns: Store ID | Revenue | Orders | Performance 
 
Tasks: 
1. Create the 2D array.  
2. Display shape and ndim.  
3. Extract Store IDs.  
4. Extract Revenue.  
5. Extract Orders.  
6. Extract Performance.  
7. Find average revenue.  
8. Find highest individual revenue.  
9. Reshape the array into a suitable shape with the same number of elements.  
10. Flatten the reshaped array and display its shape.  
11. Transpose the original array.  
12. Display the shape of the transposed array.  
13. Increase only Revenue by 10%.  
14. Find the new highest individual revenue.
"""

data = [ 
    [101, 12000, 8, 72], 
    [102, 18500, 11, 85], 
    [103, 15000, 9, 68], 
    [104, 22000, 14, 91], 
    [105, 17500, 10, 77], 
    [106, 25000, 16, 88] 
]

arr = np.array(data)

print(f"Array : {arr}")
print(f"shape : {arr.shape}")
print(f"ndim : {arr.ndim}")
print(f"Store IDs : {arr[:,0]}")
print(f"Revenue : {arr[:,1]}")
print(f"Orders : {arr[:,2]}")
print(f"Performance : {arr[:,3]}")
print(f"average revenue : {arr[:,1].mean()}")
print(f"highest individual revenue : {arr[:,1].max()}")

re = arr.reshape(3,-1)

print(f"reshape array : {re}")

flat = re.flatten()

print(f"flatten array : {flat}")
print(f"shape : {flat.shape}")

trans = arr.transpose()

print(f"transpose array : {trans}")
print(f"shape : {trans.shape}")

increased = arr.copy()
increased[:,1] = increased[:,1] + (increased[:,1] * 10) / 100

print(f"new highest individual revenue : {increased.max()}")


Array : [[  101 12000     8    72]
 [  102 18500    11    85]
 [  103 15000     9    68]
 [  104 22000    14    91]
 [  105 17500    10    77]
 [  106 25000    16    88]]
shape : (6, 4)
ndim : 2
Store IDs : [101 102 103 104 105 106]
Revenue : [12000 18500 15000 22000 17500 25000]
Orders : [ 8 11  9 14 10 16]
Performance : [72 85 68 91 77 88]
average revenue : 18333.333333333332
highest individual revenue : 25000
reshape array : [[  101 12000     8    72   102 18500    11    85]
 [  103 15000     9    68   104 22000    14    91]
 [  105 17500    10    77   106 25000    16    88]]
flatten array : [  101 12000     8    72   102 18500    11    85   103 15000     9    68
   104 22000    14    91   105 17500    10    77   106 25000    16    88]
shape : (24,)
transpose array : [[  101   102   103   104   105   106]
 [12000 18500 15000 22000 17500 25000]
 [    8    11     9    14    10    16]
 [   72    85    68    91    77    88]]
shape : (4, 6)
new highest individual revenue : 27500
