In [2]:
#1 Create a NumPy array from the following Python list: 

import numpy as np

sales = [1200, 1500, 1100, 1800, 2100] 

arr = np.array(sales)

print(arr)

[1200 1500 1100 1800 2100]


In [4]:
#2 Create a NumPy array from: 

prices = [99, 149, 299, 499, 799] 

arr = np.array(prices)

print(arr)
print(type(arr))

[ 99 149 299 499 799]
<class 'numpy.ndarray'>


In [5]:
#3 
"""
A company collected these customer ratings: 
Convert the list into a NumPy array and print it. 
"""

ratings = [4, 5, 3, 4, 2, 5, 4] 

arr = np.array(ratings)

print(arr)

[4 5 3 4 2 5 4]


In [7]:
#4
"""
Create a NumPy array from: 
Then print the array and identify whether it is a NumPy array. 
"""

salary = [25000, 32000, 28000, 45000, 38000] 

arr = np.array(salary)

print(arr)
print(type(arr))

[25000 32000 28000 45000 38000]
<class 'numpy.ndarray'>


In [10]:
#5
"""
The quantity sold for five products is: 
Convert it into a NumPy array. 
Then calculate the total quantity sold using NumPy. 
"""

quantity = [15, 22, 18, 30, 25] 

arr = np.array(quantity).sum()

print(arr)

110


In [12]:
#6 Create a NumPy array and find the average temperature. 

temperature = [31, 33, 32, 35, 34, 30, 29] 

arr = np.array(temperature).mean()

print(arr)

32.0


In [15]:
#7
"""
Create a NumPy array and find: 
 Total revenue  
 Average monthly revenue 
"""

revenue = [45000, 52000, 48000, 61000, 58000, 70000] 

total = np.array(revenue).sum()
avg = np.array(revenue).mean()

print(f"Total revenue : {total}")
print(f"Average monthly revenue : {avg}")

Total revenue : 334000
Average monthly revenue : 55666.666666666664


In [ ]:
#8
"""
Convert it into a NumPy array. 
Then try multiplying the NumPy array by 2 and observe the result. 
Also try multiplying the original Python list by 2. 
Explain the difference in the output.
"""

data = [10, 20, 30, 40, 50] 

arr = np.array(data)

arr_multi = arr * 2  # every element is multiply by 2
list_multi = data * 2  # whole list multiply by 2

print(arr_multi) 
print(list_multi)

[ 20  40  60  80 100]
[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]


In [19]:
#9 
"""
You have the following number of orders received by a company each day: 

Using NumPy: 
1. Convert the data into an array.  
2. Find total orders.  
3. Find average daily orders. 
"""

orders = [120, 135, 98, 150, 175, 160, 142] 

total = np.array(orders).sum()
avg = np.array(orders).mean()

print(f"Total orders : {total}")
print(f"Average daily orders : {avg}")

Total orders : 980
Average daily orders : 140.0


In [20]:
#10
"""
Using NumPy, create an array and find: 
1. Total sales  
2. Average sales  
3. Highest sales  
4. Lowest sales
"""

sales = [250, 400, 350, 500, 450] 

total = np.array(sales).sum()
avg = np.array(sales).mean()
highest = np.array(sales).max()
lowest = np.array(sales).min()

print(f"Total sales : {total}")
print(f"Average sales : {avg}")
print(f"Highest sales : {highest}")
print(f"Lowest sales : {lowest}")

Total sales : 1950
Average sales : 390.0
Highest sales : 500
Lowest sales : 250
