<a href="https://colab.research.google.com/github/jemin009/Numpy/blob/main/NP11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import pandas as pd

In [25]:
df = pd.read_csv(r"/content/4train.csv")

### Q1 - Fare Analysis with Array Iteration

Use the Fare column and create a NumPy array.

Perform the following using array iteration:
1. Print every Fare value.  
2. Print only Fares greater than ₹100.  
3. Count passengers whose Fare is greater than ₹100.  
4. Calculate the total Fare using iteration.

In [26]:
fare = df['Fare'].to_numpy()

In [27]:
#1
for value in fare:
  print(value)

7.25
71.2833
7.925
53.1
8.05
8.4583
51.8625
21.075
11.1333
30.0708
16.7
26.55
8.05
31.275
7.8542
16.0
29.125
13.0
18.0
7.225
26.0
13.0
8.0292
35.5
21.075
31.3875
7.225
263.0
7.8792
7.8958
27.7208
146.5208
7.75
10.5
82.1708
52.0
7.2292
8.05
18.0
11.2417
9.475
21.0
7.8958
41.5792
7.8792
8.05
15.5
7.75
21.6792
17.8
39.6875
7.8
76.7292
26.0
61.9792
35.5
10.5
7.2292
27.75
46.9
7.2292
80.0
83.475
27.9
27.7208
15.2458
10.5
8.1583
7.925
8.6625
10.5
46.9
73.5
14.4542
56.4958
7.65
7.8958
8.05
29.0
12.475
9.0
9.5
7.7875
47.1
10.5
15.85
34.375
8.05
263.0
8.05
8.05
7.8542
61.175
20.575
7.25
8.05
34.6542
63.3583
23.0
26.0
7.8958
7.8958
77.2875
8.6542
7.925
7.8958
7.65
7.775
7.8958
24.15
52.0
14.4542
8.05
9.825
14.4583
7.925
7.75
21.0
247.5208
31.275
73.5
8.05
30.0708
13.0
77.2875
11.2417
7.75
7.1417
22.3583
6.975
7.8958
7.05
14.5
26.0
13.0
15.0458
26.2833
53.1
9.2167
79.2
15.2458
7.75
15.85
6.75
11.5
36.75
7.7958
34.375
26.0
13.0
12.525
66.6
8.05
14.5
7.3125
61.3792
7.7333
8.05
8.6625
69.55
16.1
15.

In [28]:
#2
for value in fare:
  if value > 100:
    print(value)

263.0
146.5208
263.0
247.5208
146.5208
113.275
512.3292
153.4625
135.6333
151.55
247.5208
151.55
110.8833
108.9
262.375
164.8667
134.5
135.6333
153.4625
133.65
134.5
263.0
135.6333
211.5
227.525
120.0
113.275
120.0
263.0
151.55
108.9
221.7792
106.425
106.425
110.8833
227.525
110.8833
153.4625
113.275
133.65
512.3292
211.3375
110.8833
227.525
151.55
227.525
211.3375
512.3292
262.375
120.0
211.3375
120.0
164.8667


In [29]:
#3
count = 0

for value in fare:
  if value > 100:
    count += 1

print(count)

53


In [30]:
#4
total = 0

for value in fare:
  total += value

print(total)

28693.949299999967


### Q2 — Passenger Data Joining

Create two NumPy arrays:
 PassengerId  
 Survived  

Join them horizontally to create a new matrix containing:
PassengerId | Survived

Then:
1. Display its shape.  
2. Display the first 10 rows.  
3. Extract the Survived column.  


In [31]:
passenger_id = df['PassengerId'].to_numpy()
survived = df['Survived'].to_numpy()

In [32]:
mat = np.column_stack((passenger_id, survived))

mat

array([[  1,   0],
       [  2,   1],
       [  3,   1],
       ...,
       [889,   0],
       [890,   1],
       [891,   0]])

In [33]:
#1
mat.shape

(891, 2)

In [34]:
#2
mat[:10]

array([[ 1,  0],
       [ 2,  1],
       [ 3,  1],
       [ 4,  1],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  1],
       [10,  1]])

In [35]:
#3
mat[:,1]

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

### Q3 — Joining Passenger Features

Create these three NumPy arrays:

 Pclass  
 Age  
 Fare  

Join them horizontally into one matrix.

Then:
1. Display the shape.  
2. Display the first 10 rows.  
3. Find the highest individual Fare.  
4. Find the average Age.

In [38]:
pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
fare = df['Fare'].to_numpy()

In [39]:
mat = np.column_stack((pclass, age, fare))

mat

array([[ 3.    , 22.    ,  7.25  ],
       [ 1.    , 38.    , 71.2833],
       [ 3.    , 26.    ,  7.925 ],
       ...,
       [ 3.    ,     nan, 23.45  ],
       [ 1.    , 26.    , 30.    ],
       [ 3.    , 32.    ,  7.75  ]])

In [40]:
print(mat.shape)

(891, 3)


In [41]:
print(mat[:10])

[[ 3.     22.      7.25  ]
 [ 1.     38.     71.2833]
 [ 3.     26.      7.925 ]
 [ 1.     35.     53.1   ]
 [ 3.     35.      8.05  ]
 [ 3.         nan  8.4583]
 [ 1.     54.     51.8625]
 [ 3.      2.     21.075 ]
 [ 3.     27.     11.1333]
 [ 2.     14.     30.0708]]


In [42]:
print(np.max(mat[:2]))

71.2833


In [43]:
print(np.mean(mat[:1]))

10.75


### Q4 — Splitting Passenger Data
Create a NumPy matrix using:
PassengerId, Survived, Pclass, Age, Fare

Split the matrix vertically into 3 equal parts.

Then:
1. Display the shape of each part.  
2. Display the first row of each part.

In [52]:
passenger_id = df['PassengerId'].to_numpy()
survived = df['Survived'].to_numpy()
pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
fare = df['Fare'].to_numpy()

In [56]:
mat = np.column_stack((passenger_id, survived, pclass, age, fare))

mat

array([[  1.    ,   0.    ,   3.    ,  22.    ,   7.25  ],
       [  2.    ,   1.    ,   1.    ,  38.    ,  71.2833],
       [  3.    ,   1.    ,   3.    ,  26.    ,   7.925 ],
       ...,
       [889.    ,   0.    ,   3.    ,      nan,  23.45  ],
       [890.    ,   1.    ,   1.    ,  26.    ,  30.    ],
       [891.    ,   0.    ,   3.    ,  32.    ,   7.75  ]])

In [58]:
parts = np.array_split(mat, 3)

parts

[array([[  1.    ,   0.    ,   3.    ,  22.    ,   7.25  ],
        [  2.    ,   1.    ,   1.    ,  38.    ,  71.2833],
        [  3.    ,   1.    ,   3.    ,  26.    ,   7.925 ],
        ...,
        [295.    ,   0.    ,   3.    ,  24.    ,   7.8958],
        [296.    ,   0.    ,   1.    ,      nan,  27.7208],
        [297.    ,   0.    ,   3.    ,  23.5   ,   7.2292]]),
 array([[298.    ,   0.    ,   1.    ,   2.    , 151.55  ],
        [299.    ,   1.    ,   1.    ,      nan,  30.5   ],
        [300.    ,   1.    ,   1.    ,  50.    , 247.5208],
        ...,
        [592.    ,   1.    ,   1.    ,  52.    ,  78.2667],
        [593.    ,   0.    ,   3.    ,  47.    ,   7.25  ],
        [594.    ,   0.    ,   3.    ,      nan,   7.75  ]]),
 array([[595.  ,   0.  ,   2.  ,  37.  ,  26.  ],
        [596.  ,   0.  ,   3.  ,  36.  ,  24.15],
        [597.  ,   1.  ,   2.  ,    nan,  33.  ],
        ...,
        [889.  ,   0.  ,   3.  ,    nan,  23.45],
        [890.  ,   1.  ,   1.  ,  26.

In [59]:
for part in parts:
    print(part.shape)
    print(part[0])

(297, 5)
[ 1.    0.    3.   22.    7.25]
(297, 5)
[298.     0.     1.     2.   151.55]
(297, 5)
[595.   0.   2.  37.  26.]


### Q5 — Splitting Features
Create a NumPy matrix using:
Pclass, Age, SibSp, Parch, Fare

Split it column-wise into 2 parts:

 Part 1 → first 3 columns  
 Part 2 → last 2 columns  

Display both resulting matrices and their shapes.

In [72]:
pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()

In [73]:
mat = np.column_stack((pclass, age, sibsp, parch, fare))

mat

array([[ 3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 3.    ,     nan,  1.    ,  2.    , 23.45  ],
       [ 1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 3.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [74]:
part1 = np.array_split(mat, 3, axis=1)
part2 = np.array_split(mat, 2, axis=1)

In [75]:
part1

[array([[ 3., 22.],
        [ 1., 38.],
        [ 3., 26.],
        ...,
        [ 3., nan],
        [ 1., 26.],
        [ 3., 32.]]),
 array([[1., 0.],
        [1., 0.],
        [0., 0.],
        ...,
        [1., 2.],
        [0., 0.],
        [0., 0.]]),
 array([[  7.25  ],
        [ 71.2833],
        [  7.925 ],
        [ 53.1   ],
        [  8.05  ],
        [  8.4583],
        [ 51.8625],
        [ 21.075 ],
        [ 11.1333],
        [ 30.0708],
        [ 16.7   ],
        [ 26.55  ],
        [  8.05  ],
        [ 31.275 ],
        [  7.8542],
        [ 16.    ],
        [ 29.125 ],
        [ 13.    ],
        [ 18.    ],
        [  7.225 ],
        [ 26.    ],
        [ 13.    ],
        [  8.0292],
        [ 35.5   ],
        [ 21.075 ],
        [ 31.3875],
        [  7.225 ],
        [263.    ],
        [  7.8792],
        [  7.8958],
        [ 27.7208],
        [146.5208],
        [  7.75  ],
        [ 10.5   ],
        [ 82.1708],
        [ 52.    ],
        [  7.2292],
  

In [68]:
part2

[array([[ 3., 22.,  1.],
        [ 1., 38.,  1.],
        [ 3., 26.,  0.],
        ...,
        [ 3., nan,  1.],
        [ 1., 26.,  0.],
        [ 3., 32.,  0.]]),
 array([[ 0.    ,  7.25  ],
        [ 0.    , 71.2833],
        [ 0.    ,  7.925 ],
        ...,
        [ 2.    , 23.45  ],
        [ 0.    , 30.    ],
        [ 0.    ,  7.75  ]])]

In [76]:
for i in part1:
  print(i.shape)

(891, 2)
(891, 2)
(891, 1)


In [78]:
for i in part2:
  print(i.shape)

(891, 3)
(891, 2)


### Q6 — Searching Passenger Fares
Create a NumPy array from Fare.

Using NumPy searching functions:
1. Find the indexes where Fare is greater than ₹200.  
2. Count how many such passengers exist.  
3. Find the indexes where Fare is exactly 0.  
4. Find the first index where Fare is greater than ₹500.

In [79]:
fare = df['Fare'].to_numpy()

fare

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
         7.8958,  41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,
        21.6792,  17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,
         7.2292,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,   8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,
        29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,   8.05  , 263.    ,   8.0

In [92]:
print(np.where(fare > 200))

(array([ 27,  88, 118, 258, 299, 311, 341, 377, 380, 438, 527, 557, 679,
       689, 700, 716, 730, 737, 742, 779]),)


In [87]:
print(np.count_nonzero(fare > 200))

20


In [135]:
print(np.where(fare == 0))

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),)


In [95]:
print(np.where(fare > 500)[0][0])

258


### Q7 — Sorting Fares
Create a NumPy array from Fare.

Perform:
1. Sort the Fare values in ascending order.  
2. Display the first 10 values.  
3. Display the last 10 values.  
4. Find the index positions that would sort the original Fare array.  
5. Use those indexes to identify the 5 passengers who paid the highest Fares
using PassengerId.

In [98]:
fare = df['Fare'].to_numpy()

fare

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
         7.8958,  41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,
        21.6792,  17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,
         7.2292,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,   8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,
        29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,   8.05  , 263.    ,   8.0

In [101]:
print(np.sort(fare))

[  0.       0.       0.       0.       0.       0.       0.       0.
   0.       0.       0.       0.       0.       0.       0.       4.0125
   5.       6.2375   6.4375   6.45     6.4958   6.4958   6.75     6.75
   6.8583   6.95     6.975    6.975    7.0458   7.05     7.05     7.05
   7.05     7.05     7.05     7.05     7.0542   7.0542   7.125    7.125
   7.125    7.125    7.1417   7.225    7.225    7.225    7.225    7.225
   7.225    7.225    7.225    7.225    7.225    7.225    7.225    7.2292
   7.2292   7.2292   7.2292   7.2292   7.2292   7.2292   7.2292   7.2292
   7.2292   7.2292   7.2292   7.2292   7.2292   7.2292   7.25     7.25
   7.25     7.25     7.25     7.25     7.25     7.25     7.25     7.25
   7.25     7.25     7.25     7.3125   7.4958   7.4958   7.4958   7.5208
   7.55     7.55     7.55     7.55     7.6292   7.65     7.65     7.65
   7.65     7.725    7.7292   7.7333   7.7333   7.7333   7.7333   7.7375
   7.7375   7.7417   7.75     7.75     7.75     7.75     7.75     7

In [102]:
print(fare[:10])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [103]:
print(fare[-10:])

[247.5208 262.375  262.375  263.     263.     263.     263.     512.3292
 512.3292 512.3292]


In [104]:
print(np.argsort(fare))

[  0   1   2   8  14  13  12  11   6   9   7  10   4   5   3  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  33  29  30  34  31  32  35
  36  37  40  39  41  38  42  51  52  53  54  50  49  48  47  46  45  44
  43  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 122 123
 124 125 126 127 112 113 114 115 116 117 118 119 120 121 106 107 108 109
 110 111 135 134 133 132 139 138 137 136 131 130 129 128 143 142 141 140
 151 150 149 148 155 154 153 152 147 146 145 144 156 159 157 158 161 162
 160 163 165 164 175 174 167 166 173 172 171 170 169 168 176 178 177 179
 180 183 181 182 184 219 220 221 222 215 216 217 218 214 213 212 211 191
 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209
 210 187 188 189 190 185 186 236 235 239 240 237 238 226 225 224 223 230
 229 232 231 228 227 233 234 241 257 258 255 254 25

In [108]:
print(df.iloc[np.argsort(fare)[-5:]])

     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
884          885         0       3                    Sutehall, Mr. Henry Jr   
889          890         1       1                     Behr, Mr. Karl Howell   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch           Ticket      Fare Cabin Embarked  
886    male  27.0      0      0           211536  263.0000   NaN        S  
884    male  25.0      0      0  SOTON/OQ 392076  263.0000   NaN        S  
889    male  26.0      0      0           111369  512.3292  C148        C  
888  female   NaN      1      2       W./C. 6607  512.3292   NaN        S  
890    male  32.0      0      0           370376  512.3292   NaN        Q  


### Q8 — Copy vs View
Create a NumPy array using the first 10 Fare values.

Create:

 one view  
 one copy  

Modify the first value of the view by adding ₹100.
Then check whether the original array changed.

After that, modify the first value of the copy by adding ₹200 and check whether the
original array changed.

In [120]:
fare = df['Fare'][:10].to_numpy()

fare

array([100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [124]:
view = fare.view()
copy = fare.copy()

print(view)
print(copy)

[100.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
[100.   0.   0.   0.   0.   0.   0.   0.   0.   0.]


In [122]:
view[0] = 100

view

array([100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

In [123]:
copy[0] = 200

copy

array([200.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])

### Q9 — Broadcasting Fare Adjustment
Create a matrix containing:
Pclass, Age, SibSp, Parch, Fare

Increase only the Fare column by 10% using broadcasting.

Then:
1. Display the first 10 rows before modification.  
2. Display the first 10 rows after modification.  
3. Find the new highest Fare.

In [126]:
pclass = df['Pclass'].to_numpy()
age = df['Age'].to_numpy()
sibsp = df['SibSp'].to_numpy()
parch = df['Parch'].to_numpy()
fare = df['Fare'].to_numpy()

In [127]:
mat = np.column_stack((pclass, age, sibsp, parch, fare))

mat

array([[  3.    ,  22.    ,   1.    ,   0.    , 100.    ],
       [  1.    ,  38.    ,   1.    ,   0.    ,   0.    ],
       [  3.    ,  26.    ,   0.    ,   0.    ,   0.    ],
       ...,
       [  3.    ,      nan,   1.    ,   2.    , 512.3292],
       [  1.    ,  26.    ,   0.    ,   0.    , 512.3292],
       [  3.    ,  32.    ,   0.    ,   0.    , 512.3292]])

In [131]:
print(mat[:10])

[[  3.  22.   1.   0. 100.]
 [  1.  38.   1.   0.   0.]
 [  3.  26.   0.   0.   0.]
 [  1.  35.   1.   0.   0.]
 [  3.  35.   0.   0.   0.]
 [  3.  nan   0.   0.   0.]
 [  1.  54.   0.   0.   0.]
 [  3.   2.   3.   1.   0.]
 [  3.  27.   0.   2.   0.]
 [  2.  14.   1.   0.   0.]]


In [137]:
mat[:, 4] = mat[:, 4] * 10 / 100 + mat[:, 4]

mat

array([[  3.       ,  22.       ,   1.       ,   0.       , 133.1      ],
       [  1.       ,  38.       ,   1.       ,   0.       ,   0.       ],
       [  3.       ,  26.       ,   0.       ,   0.       ,   0.       ],
       ...,
       [  3.       ,         nan,   1.       ,   2.       , 681.9101652],
       [  1.       ,  26.       ,   0.       ,   0.       , 681.9101652],
       [  3.       ,  32.       ,   0.       ,   0.       , 681.9101652]])

In [138]:
print(mat[:10])

[[  3.   22.    1.    0.  133.1]
 [  1.   38.    1.    0.    0. ]
 [  3.   26.    0.    0.    0. ]
 [  1.   35.    1.    0.    0. ]
 [  3.   35.    0.    0.    0. ]
 [  3.    nan   0.    0.    0. ]
 [  1.   54.    0.    0.    0. ]
 [  3.    2.    3.    1.    0. ]
 [  3.   27.    0.    2.    0. ]
 [  2.   14.    1.    0.    0. ]]


In [139]:
print(np.max(mat[:, 4]))

681.9101652


In [ ]:
from google.colab import drive
drive.mount('/content/drive')